## Nim API code generator for WebCC.
## Generates per-namespace Nim API files and handles.nim from parsed schema.

import std/[strutils, tables, os]
import bindwebschema

# ------------------------------------------------------------------------------
# Templates for generated code sections
# ------------------------------------------------------------------------------

const FILE_HEADER = """## Generated by WebCC - DO NOT EDIT
## Source: schema.def

"""

const CORE_IMPORTS = """import bindweb, bindwebtypes

"""

# ------------------------------------------------------------------------------
# Helper: generate the pushData call for a parameter type
# ------------------------------------------------------------------------------
proc pushDataCall(p: SchemaParam; paramName: string): string =
  case p.paramType:
    of ptInt32: "pushData(" & paramName & ".int32)"
    of ptUint32: "pushData(" & paramName & ".uint32)"
    of ptUint8: "pushData(" & paramName & ".uint32)"  # uint8 pushed as uint32 for alignment
    of ptFloat32: "pushData(" & paramName & ".float32)"
    of ptFloat64: "pushData(" & paramName & ".float64)"
    of ptString: "pushString(" & paramName & ")"
    of ptHandle: "pushData(" & paramName & ".int32)"
    of ptFuncPtr: "pushData(cast[uint32](" & paramName & "))"

# ------------------------------------------------------------------------------
# Helper: generate C parameter declaration for importc proc
# ------------------------------------------------------------------------------
proc cParamList(p: SchemaParam; index: int): seq[string] =
  ## Return a list of C parameter declarations for this schema parameter.
  ## Strings produce two parameters (cstring + uint32 length).
  let name = nimParamName(p.name, index)
  case p.paramType:
    of ptInt32, ptHandle: result.add(name & ": int32")
    of ptUint32: result.add(name & ": uint32")
    of ptUint8: result.add(name & ": uint32")  # passed as uint32 for alignment
    of ptFloat32: result.add(name & ": float32")
    of ptFloat64: result.add(name & ": float64")
    of ptString:
      result.add(name & ": cstring")
      result.add(name & "Len: uint32")
    of ptFuncPtr: result.add(name & ": uint32")

# ------------------------------------------------------------------------------
# Helper: generate argument for calling the C import proc
# ------------------------------------------------------------------------------
proc cCallArg(p: SchemaParam; paramName: string): string =
  case p.paramType:
    of ptInt32, ptUint32, ptFloat32, ptFloat64, ptFuncPtr:
      paramName
    of ptUint8:
      paramName & ".uint32"
    of ptString:
      paramName & ".cstring, " & paramName & ".len.uint32"
    of ptHandle:
      "int32(" & paramName & ")"

# ------------------------------------------------------------------------------
# Generate handles.nim
# ------------------------------------------------------------------------------
proc generateHandles*(defs: SchemaDefs; outDir: string) =
  var content = FILE_HEADER
  content.add("## Typed handle definitions\n\n")
  content.add("import bindwebtypes\n\n")
  content.add("export Handle\n\n")
  content.add("type\n")

  # Inheritance-aware ordering
  let handleTypes = defs.orderedHandleTypes()

  for ht in handleTypes:
    var baseStr = ""
    if defs.handleInheritance.hasKey(ht):
      baseStr = defs.handleInheritance[ht] & "Handle"
    else:
      baseStr = "Handle"

    content.add("  " & ht & "Handle* = distinct int32\n")
    content.add("    ## Handle for " & ht & "\n")
    if baseStr != "":
      content.add("    ## Inherits from " & baseStr & "\n")
    content.add("\n")

  # Add converter procs for inheritance
  content.add("# ------------------------------------------------------------------------------\n")
  content.add("# Inheritance converters\n")
  content.add("# ------------------------------------------------------------------------------\n\n")

  for ht in handleTypes:
    if defs.handleInheritance.hasKey(ht):
      let base = defs.handleInheritance[ht]
      content.add("converter to" & base & "Handle*(h: " & ht & "Handle): " & base & "Handle =\n")
      content.add("  " & base & "Handle(h.int32)\n\n")

  # Add comparison operators
  content.add("# ------------------------------------------------------------------------------\n")
  content.add("# Handle comparison operators\n")
  content.add("# ------------------------------------------------------------------------------\n\n")

  for ht in handleTypes:
    let hname = ht & "Handle"
    content.add("proc `==`*(a, b: " & hname & "): bool = a.int32 == b.int32\n")
    content.add("proc `!=`*(a, b: " & hname & "): bool = a.int32 != b.int32\n")
    content.add("proc isValid*(h: " & hname & "): bool = h.int32 != 0\n\n")

  let outPath = outDir / "handles.nim"
  writeFile(outPath, content)
  echo "Generated: ", outPath

# ------------------------------------------------------------------------------
# Generate per-namespace Nim API file
# ------------------------------------------------------------------------------
proc generateNamespaceApi*(defs: SchemaDefs; ns: string; outDir: string) =
  let cmds = defs.getCommands(ns)
  let evts = defs.getEvents(ns)

  if cmds.len == 0 and evts.len == 0:
    return

  var content = FILE_HEADER
  content.add("## " & ns.toUpperAscii() & " namespace API\n\n")
  content.add(CORE_IMPORTS)
  content.add("import handles\n\n")

  # ---------------------------------------------------------------------------
  # Event type definitions
  # ---------------------------------------------------------------------------
  if evts.len > 0:
    # -------------------------------------------------------------------------
    # Event opcode constants
    # -------------------------------------------------------------------------
    # Emitted as named constants (e.g. CLICK_EVENT_OPCODE) so higher-level
    # layers like bindwebevents.nim can match on them by name instead of magic
    # numbers. The value is the global sequential opcode assigned in
    # bindwebschema.nim and must stay in lock-step with the JS runtime's
    # push_event_* functions.
    content.add("# ------------------------------------------------------------------------------\n")
    content.add("# Event opcode constants\n")
    content.add("# ------------------------------------------------------------------------------\n\n")
    content.add("const\n")
    for evt in evts:
      content.add("  " & evt.name & "_EVENT_OPCODE* = 0x" & toHex(evt.opcode.int, 2) & "'u8\n")
    content.add("\n")

    content.add("# ------------------------------------------------------------------------------\n")
    content.add("# Event types\n")
    content.add("# ------------------------------------------------------------------------------\n\n")
    content.add("type\n")

    for evt in evts:
      let structName = eventStructName(evt.name)
      content.add("  " & structName & "* = object\n")
      content.add("    ## Event: " & evt.name & " (opcode 0x" & toHex(evt.opcode.int, 2) & ")\n")
      for p in evt.params:
        content.add("    " & p.name & "*: " & nimType(p) & "\n")
      content.add("\n")

    # Generate parse procs
    content.add("# ------------------------------------------------------------------------------\n")
    content.add("# Event parsing\n")
    content.add("# ------------------------------------------------------------------------------\n\n")

    for evt in evts:
      let structName = eventStructName(evt.name)
      content.add("proc parse" & structName & "*(data: ptr uint8; len: uint32): " & structName & " =\n")
      content.add("  ## Parse " & evt.name & " event from raw event buffer data.\n")
      content.add("  var offset: uint32 = 0\n")

      for p in evt.params:
        case p.paramType:
          of ptInt32, ptHandle:
            content.add("  result." & p.name & " = cast[" & nimType(p) & "](readInt32(data, offset))\n")
          of ptUint32:
            content.add("  result." & p.name & " = readUint32(data, offset)\n")
          of ptUint8:
            content.add("  result." & p.name & " = uint8(readUint32(data, offset))\n")
          of ptFloat32:
            content.add("  result." & p.name & " = readFloat32(data, offset)\n")
          of ptFloat64:
            content.add("  result." & p.name & " = readFloat64(data, offset)\n")
          of ptString:
            content.add("  result." & p.name & " = readString(data, offset)\n")
          of ptFuncPtr:
            content.add("  result." & p.name & " = cast[pointer](readInt32(data, offset))\n")
      content.add("\n")

    content.add("\n")

  # ---------------------------------------------------------------------------
  # Void commands: push opcode + data
  # ---------------------------------------------------------------------------
  var voidCmds: seq[SchemaCommand]
  var retCmds: seq[SchemaCommand]

  for c in cmds:
    if c.returnType == "":
      voidCmds.add(c)
    else:
      retCmds.add(c)

  if voidCmds.len > 0:
    content.add("# ------------------------------------------------------------------------------\n")
    content.add("# Void commands (push to command buffer)\n")
    content.add("# ------------------------------------------------------------------------------\n\n")

    for c in voidCmds:
      # Generate proc signature
      var procLine = "proc " & c.funcName & "*("
      for i, p in c.params:
        if i > 0: procLine.add(", ")
        procLine.add(nimParamName(p.name, i) & ": " & nimType(p))
      procLine.add(") =")
      content.add(procLine & "\n")

      # Doc comment
      content.add("  ## " & c.ns & "." & c.name & " (opcode 0x" & toHex(c.opcode.int, 2) & ")\n")

      # Body
      content.add("  pushCommand(0x" & toHex(c.opcode.int, 2) & "u32)\n")
      for i, p in c.params:
        let pname = nimParamName(p.name, i)
        content.add("  " & pushDataCall(p, pname) & "\n")
      content.add("\n")

  # ---------------------------------------------------------------------------
  # Return-value commands: importc + wrapper
  # ---------------------------------------------------------------------------
  if retCmds.len > 0:
    content.add("# ------------------------------------------------------------------------------\n")
    content.add("# Return-value commands (JS imports)\n")
    content.add("# ------------------------------------------------------------------------------\n\n")

    # Forward declarations (importc procs)
    for c in retCmds:
      let importName = "bindweb_" & c.ns & "_" & c.funcName
      var decl = "proc " & importName & "("
      var allParams: seq[string]
      for i, p in c.params:
        for cp in cParamList(p, i):
          allParams.add(cp)
      decl.add(allParams.join("; "))
      decl.add("): " & nimReturnTypeC(c))
      decl.add(" {.importc.}\n")
      content.add(decl)

    content.add("\n")

    # Nim wrapper procs
    for c in retCmds:
      let importName = "bindweb_" & c.ns & "_" & c.funcName
      let retType = nimReturnType(c)

      # Wrapper proc signature
      var procLine = "proc " & c.funcName & "*("
      for i, p in c.params:
        if i > 0: procLine.add("; ")
        procLine.add(nimParamName(p.name, i) & ": " & nimType(p))
      procLine.add("): " & retType & " =")
      content.add(procLine & "\n")

      content.add("  ## " & c.ns & "." & c.name & "\n")
      content.add("  flush()\n")

      # Generate the call
      case c.returnType:
        of "string":
          # String return: get length, read from scratch buffer
          content.add("  let strLen = " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(")\n")
          content.add("  let data = cast[cstring](bindwebScratchBufferData())\n")
          content.add("  result = newString(strLen.int)\n")
          content.add("  if strLen > 0:\n")
          content.add("    copyMem(addr result[0], data, strLen.int)\n")

        of "handle":
          # Handle return: cast int32 to handle type
          let handleType = if c.returnHandleType != "": c.returnHandleType & "Handle" else: "Handle"
          content.add("  return " & handleType & "(" & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add("))\n")

        of "float64":
          content.add("  return " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(")\n")

        of "int32":
          content.add("  return " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(")\n")

        of "uint32":
          content.add("  return " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(").uint32\n")

        of "uint8":
          content.add("  return " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(").uint8\n")

        of "float32":
          content.add("  return " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(").float32\n")

        else:
          content.add("  discard " & importName & "(")
          for i, p in c.params:
            if i > 0: content.add(", ")
            content.add(cCallArg(p, nimParamName(p.name, i)))
          content.add(")\n")

      content.add("\n")

  # Write the file
  let outPath = outDir / (ns & ".nim")
  writeFile(outPath, content)
  echo "Generated: ", outPath

# ------------------------------------------------------------------------------
# Generate all API files
# ------------------------------------------------------------------------------
proc generateAllApis*(defs: SchemaDefs; schemaPath: string; outDir: string) =
  ## Generate all Nim API files from schema definitions.
  ## schemaPath: path to schema.def (used for reference in generated comments)
  ## outDir: output directory for generated .nim files

  # Ensure output directory exists
  createDir(outDir)

  # Generate handles.nim first
  generateHandles(defs, outDir)

  # Generate per-namespace API files
  let namespaces = defs.getNamespaces()
  for ns in namespaces:
    generateNamespaceApi(defs, ns, outDir)

  echo "\nGenerated ", namespaces.len + 1, " files in ", outDir

# ------------------------------------------------------------------------------
# When run standalone
# ------------------------------------------------------------------------------
when isMainModule:
  let schemaPath = "src/schema.def"
  let outDir = "src/nim/apis"

  echo "Loading schema from ", schemaPath, "..."
  let defs = loadSchema(schemaPath)
  echo "Loaded ", defs.commands.len, " commands, ", defs.events.len, " events"
  echo "Namespaces: ", defs.getNamespaces()
  echo "Handle types: ", defs.collectHandleTypes()

  echo "\nGenerating Nim API files..."
  generateAllApis(defs, schemaPath, outDir)
