/**
 * main.js — UI glue for the nim-wasm-compiler IDE (SPEC §8c:
 * non-programmer-friendly, one big Run button, examples, honest
 * download progress, friendly errors).
 *
 * Wires the editor, console log pane and app output pane to the compile
 * pipeline (web/src/pipeline.js). No frameworks, no bundler: plain ES
 * modules loaded via <script type="module">.
 *
 * Served from the dist root (tools/make-dist.sh copies web/ to dist/), so
 * vendor/ and libpacks/ are sibling directories — see `config` below.
 *
 * Download progress: the big vendor wasm files are fetched ONCE here with
 * a ReadableStream reader so the byte count (and MB label) is real. The
 * fetched nim.wasm / nim-bundle.data bytes are handed to the Nim compiler
 * as blob: URLs through its `preloaded` option, so those are never
 * downloaded twice. The clang worker re-fetches its own files by URL
 * inside a Web Worker (no way to hand it blobs from here); on a served
 * dist the browser HTTP cache normally makes that second read free.
 */

import { NimCompiler } from './nim-compiler.js';
import { ClangCompiler } from './clang-compiler.js';
import { compileAndRun } from './pipeline.js';
import { createBindwebRunner } from './runtime/bindweb-browser-runtime.js';

/**
 * Dist-layout config: index.html sits at the dist root next to vendor/
 * (populated by build.sh) and libpacks/ (generated by tools/pack-lib.sh).
 */
const config = { vendorUrl: './vendor', libpacksUrl: './libpacks' };

/**
 * The big toolchain files, with their known sizes in bytes (measured on the
 * pinned clang.js@0.1.1 npm artifacts + nim.wasm build; used only as the
 * progress-bar denominator — actual bytes are counted as they stream in, so
 * a rebuilt nim.wasm with a different size is fine). Total is about 73 MB.
 */
const VENDOR_FILES = [
  { path: 'clang/clang.wasm', size: 31214472, label: 'C compiler' },
  { path: 'clang/lld.wasm', size: 19490094, label: 'linker' },
  { path: 'clang/sysroot.tar', size: 9297920, label: 'C library' },
  { path: 'clang/memfs.wasm', size: 345442, label: 'C library helper' },
  { path: 'clang/clang.js', size: 19214, label: 'C compiler glue' },
  { path: 'nim/nim.wasm', size: 4812366, label: 'Nim compiler' },
  { path: 'nim/nim-bundle.js', size: 6566418, label: 'Nim compiler glue' },
  // NOTE: no nim-bundle.data — this build ships the stdlib/config as libpacks
  // (mounted into MEMFS at run time), and emcc is invoked without --preload-file,
  // so no .data blob is produced. Prefetching it only yielded a harmless 404.
];

/* --------------------------------------------------------------------------
 * Example programs. Written against the bindweb APIs (see Bindweb/examples
 * and the generated apis/*.nim). Nim identifiers are style-insensitive after
 * the first character, so camelCase calls map to the snake_case definitions.
 * ------------------------------------------------------------------------ */

const EXAMPLE_BUTTONS = `## Buttons -- JS event + Nim closure (WebApp).
## Button 1 is wired with raw JavaScript via inject_script.
## Button 2 is wired with a real Nim callback that captures a local,
## which is what the WebApp event system needs on the WASM backend.

import bindweb, bindwebtypes, bindwebevents
import apis/handles, apis/dom, apis/system

proc main() =
  let body = getBody()

  let container = createElement("div")
  setAttribute(container, "style", "padding:24px; max-width:640px; margin:0 auto; font-family:sans-serif;")
  appendChild(body, container)

  let title = createElement("h1")
  setAttribute(title, "style", "color:#e6edf3;")
  setInnerText(title, "Nim Bindweb DOM Demo")
  appendChild(container, title)

  let subtitle = createElement("p")
  setAttribute(subtitle, "style", "color:#9aa4af; margin-bottom:16px;")
  setInnerText(subtitle, "Button 1 runs JavaScript. Button 2 fires a Nim callback via WebApp.")
  appendChild(container, subtitle)

  # --- Button 1: pure JavaScript via inject_script + addEventListener ---

  let jsBtn = createElement("button")
  setAttribute(jsBtn, "id", "js-color-btn")
  setAttribute(jsBtn, "style", "padding:12px 24px; background:#2196F3; color:#fff; border:none; border-radius:6px; cursor:pointer; font-size:16px; margin-right:8px;")
  setInnerText(jsBtn, "JS: Change Color")
  appendChild(container, jsBtn)

  inject_script("""

    document.getElementById('js-color-btn').addEventListener('click', function(e) {

      e.currentTarget.style.background = '#' + Math.floor(Math.random() * 16777215).toString(16);

    });

  """)

  # --- Button 2: Nim callback via WebApp event system ---

  let nimBtn = createElement("button")
  setAttribute(nimBtn, "style", "padding:12px 24px; background:#4CAF50; color:#fff; border:none; border-radius:6px; cursor:pointer; font-size:16px;")
  setInnerText(nimBtn, "Nim: Click Me!")
  appendChild(container, nimBtn)

  addClickListener(nimBtn)

  let nimResult = createElement("div")
  setAttribute(nimResult, "style", "margin-top:14px; padding:12px; background:#0f2417; border:1px solid #2e7d32; border-radius:6px; color:#7ee787;")
  setInnerText(nimResult, "Status: click the green button - WebApp will dispatch to onClick.")
  appendChild(container, nimResult)

  setTitle("Nim Bindweb DOM Demo")
  flush()

  # --- High-level WebApp event system. clickCount + nimResult are LOCALS, so
  # this handler captures them -> it is a real closure (env != nil), which is the
  # calling convention the dispatcher (and the WASM backend) handle correctly. ---

  let app = newWebApp()
  var clickCount = 0
  app.onClick = proc(ev: ClickEvent) =
    clickCount += 1
    setInnerText(nimResult,
      "Nim handled click #" & $clickCount & " via WebApp.onClick  (handle " & $ev.handle.int32 & ")")
    log("Click event dispatched: Click")
    flush()
  app.run()

main()
`;

const EXAMPLE_ROTATE = `## Rotating canvas -- a 60 FPS animated Canvas 2D scene.
## Uses setMainLoop with a top-level update proc; the rotation state is a
## module-level var so the proc can mutate it on every frame.

import bindweb, bindwebtypes

import apis/handles, apis/dom, apis/canvas, apis/system

var
  ctx: CanvasContext2DHandle
  rotation = 0.0

proc update(timeMs: float64) =
  # Clear and draw rotating rectangle
  setFillStyle(ctx, 30, 30, 50)
  fillRect(ctx, 0, 0, 600, 400)

  # Save context
  save(ctx)

  # Translate to center and rotate
  translate(ctx, 300.0, 200.0)
  rotate(ctx, rotation)

  # Draw colored square
  setFillStyle(ctx, 100, 200, 255)
  fillRect(ctx, -50.0, -50.0, 100.0, 100.0)

  # Draw inner square
  setFillStyle(ctx, 255, 100, 150)
  fillRect(ctx, -25.0, -25.0, 50.0, 50.0)

  restore(ctx)

  # Draw title text
  setFont(ctx, "20px Arial")
  setFillStyle(ctx, 255, 255, 255)
  fillText(ctx, "Canvas Demo from Nim!", 180.0, 30.0)

  setFont(ctx, "14px Arial")
  setFillStyle(ctx, 200, 200, 200)
  fillText(ctx, "Rotating squares with Canvas 2D", 190.0, 55.0)

  # Update rotation
  rotation += 0.02

  flush()

proc main() =
  let body = getBody()

  # Create canvas
  let canvas = createCanvas("demo-canvas", 600.0, 400.0)
  appendChild(body, canvas)

  # Get 2D context
  ctx = getContext2d(canvas)

  # Start animation loop
  setMainLoop(update)

  flush()

main()
`;

const EXAMPLE_MOUSE = `## Mouse interaction -- draw a glowing dot that follows the mouse.
## All interaction state lives as LOCALS captured by the WebApp handlers, so
## each handler is a real closure with a uniform signature (the WASM backend
## needs this: a non-capturing handler gets a different function-table
## signature and dispatching a struct event through it throws
## "function signature mismatch").

import bindweb, bindwebtypes, bindwebevents

import apis/handles, apis/dom, apis/canvas, apis/system, apis/input

proc main() =
  var
    ctx: CanvasContext2DHandle
    mouseX = 300
    mouseY = 200
    isClicking = false

  let body = getBody()
  let canvas = createCanvas("mouse-canvas", 600.0, 400.0)
  appendChild(body, canvas)
  ctx = getContext2d(canvas)
  initMouse(canvas)

  # Nested so it captures the same locals the handlers mutate.
  proc drawFrame() =
    setFillStyle(ctx, 20, 20, 35)
    fillRect(ctx, 0, 0, 600, 400)

    setStrokeStyleStr(ctx, "#333")
    setLineWidth(ctx, 1.0)
    for i in 0..<10:
      let x = float64(i * 60)
      beginPath(ctx)
      moveTo(ctx, x, 0.0)
      lineTo(ctx, x, 400.0)
      stroke(ctx)
      let y = float64(i * 40)
      beginPath(ctx)
      moveTo(ctx, 0.0, y)
      lineTo(ctx, 600.0, y)
      stroke(ctx)

    beginPath(ctx)
    arc(ctx, float64(mouseX), float64(mouseY), 30.0, 0.0, 6.28318)
    if isClicking:
      setFillStyle(ctx, 255, 80, 80)
      setShadow(ctx, 20.0, 0.0, 0.0, "red")
    else:
      setFillStyle(ctx, 80, 255, 120)
      setShadow(ctx, 10.0, 5.0, 5.0, "rgba(0,0,0,0.5)")
    fill(ctx)

    setStrokeStyleStr(ctx, "rgba(255,255,255,0.3)")
    setLineWidth(ctx, 1.0)
    beginPath(ctx)
    moveTo(ctx, float64(mouseX) - 40.0, float64(mouseY))
    lineTo(ctx, float64(mouseX) + 40.0, float64(mouseY))
    stroke(ctx)
    beginPath(ctx)
    moveTo(ctx, float64(mouseX), float64(mouseY) - 40.0)
    lineTo(ctx, float64(mouseX), float64(mouseY) + 40.0)
    stroke(ctx)

    setFont(ctx, "16px monospace")
    setFillStyle(ctx, 255, 255, 255)
    fillText(ctx, "Mouse: (" & $mouseX & ", " & $mouseY & ")", 10.0, 25.0)
    if isClicking:
      fillText(ctx, "CLICKING!", 10.0, 50.0)
    flush()

  let app = newWebApp()
  app.onMouseMove = proc(ev: MouseMoveEvent) =
    mouseX = ev.x
    mouseY = ev.y
  app.onMouseDown = proc(ev: MouseDownEvent) =
    isClicking = true
  app.onMouseUp = proc(ev: MouseUpEvent) =
    isClicking = false

  setTitle("Nim Bindweb Mouse Input Demo")
  app.webloop:
    drawFrame()

main()
`;

const EXAMPLES = [
  { id: 'buttons', label: 'Buttons (JS + WebApp)', source: EXAMPLE_BUTTONS },
  { id: 'rotate', label: 'Rotating Canvas', source: EXAMPLE_ROTATE },
  { id: 'mouse', label: 'Mouse Interaction', source: EXAMPLE_MOUSE },
];

/* --------------------------------------------------------------------------
 * DOM handles + small UI helpers.
 * ------------------------------------------------------------------------ */

const editor = document.getElementById('editor');
const lineNumbers = document.getElementById('line-numbers');
const consoleEl = document.getElementById('console');
const outputEl = document.getElementById('app-output');
const statusEl = document.getElementById('status');
const runBtn = document.getElementById('btn-run');
const examplesEl = document.getElementById('examples');
const progressWrap = document.getElementById('progress-wrap');
const progressBar = document.getElementById('progress-bar');
const progressLabel = document.getElementById('progress-label');
const errorBox = document.getElementById('error-box');
const errorSummary = document.getElementById('error-summary');
const errorRaw = document.getElementById('error-raw');

/**
 * Update the status pill.
 *
 * @param {string} text status message
 * @param {'' | 'busy' | 'ok' | 'err'} [kind] visual state
 */
function setStatus(text, kind = '') {
  statusEl.textContent = text;
  statusEl.className = kind;
}

/**
 * Append a line to the console pane.
 *
 * @param {string} msg message text
 * @param {string} [kind] 'step' | 'info' | 'ok' | 'warn' | 'error' |
 *   'stdout' | 'stderr'
 */
function log(msg, kind = 'info') {
  const line = document.createElement('div');
  line.className = `line ${kind}`;
  const stamp = document.createElement('span');
  stamp.className = 't';
  stamp.textContent = new Date().toLocaleTimeString('en-GB', { hour12: false });
  line.appendChild(stamp);
  line.appendChild(document.createTextNode(msg));
  consoleEl.appendChild(line);
  consoleEl.scrollTop = consoleEl.scrollHeight;
}

/** Show the friendly error box (SPEC §8c: never alert()). */
function showError(summary, raw) {
  errorSummary.textContent = summary;
  errorRaw.textContent = raw && raw.trim() ? raw.trim() : '(no further output)';
  errorBox.classList.add('visible');
}

/** Hide the friendly error box (on each new run). */
function hideError() {
  errorBox.classList.remove('visible');
}

/** Refresh the line-number gutter to match the editor content. */
function updateLineNumbers() {
  const count = editor.value.split('\n').length;
  const nums = new Array(count);
  for (let i = 0; i < count; i++) nums[i] = i + 1;
  lineNumbers.textContent = nums.join('\n');
  lineNumbers.scrollTop = editor.scrollTop;
}

editor.addEventListener('input', updateLineNumbers);
editor.addEventListener('scroll', () => {
  lineNumbers.scrollTop = editor.scrollTop;
});
editor.addEventListener('keydown', (e) => {
  if (e.key === 'Tab') {
    e.preventDefault();
    const { selectionStart: start, selectionEnd: end } = editor;
    editor.setRangeText('  ', start, end, 'end');
    updateLineNumbers();
  }
});

/* --------------------------------------------------------------------------
 * Examples dropdown.
 * ------------------------------------------------------------------------ */

for (const ex of EXAMPLES) {
  const opt = document.createElement('option');
  opt.value = ex.id;
  opt.textContent = ex.label;
  examplesEl.appendChild(opt);
}
examplesEl.disabled = false;

examplesEl.addEventListener('change', () => {
  const ex = EXAMPLES.find((e) => e.id === examplesEl.value);
  if (!ex) return;
  editor.value = ex.source;
  updateLineNumbers();
  hideError();
  log(`loaded example "${ex.label}" — press Run to try it`, 'info');
});

/* --------------------------------------------------------------------------
 * First-visit download with honest byte counting (SPEC §8c).
 * ------------------------------------------------------------------------ */

/** Format a byte count as a short MB string. */
function mb(bytes) {
  return (bytes / (1024 * 1024)).toFixed(0);
}

/**
 * Fetch one vendor file, counting bytes as they stream in.
 *
 * @param {{path: string, size: number, label: string}} file entry from VENDOR_FILES
 * @param {(done: number) => void} onBytes called with the cumulative count
 * @returns {Promise<Blob|null>} the file contents, or null if missing
 */
async function prefetchFile(file, onBytes) {
  const url = `${config.vendorUrl}/${file.path}`;
  let response;
  try {
    response = await fetch(url);
  } catch (e) {
    return null; // network hiccup: let the real loader surface the error
  }
  if (!response.ok || !response.body) return null; // optional file absent

  const reader = response.body.getReader();
  const chunks = [];
  let received = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    received += value.length;
    onBytes(value.length);
  }
  const type = file.path.endsWith('.wasm') ? 'application/wasm' : '';
  return new Blob(chunks, { type });
}

/**
 * Download every vendor file once, narrating progress in MB. Returns the
 * nim files as blobs so NimCompiler can load them from blob: URLs instead
 * of fetching them a second time.
 *
 * @returns {Promise<Map<string, Blob>>} basename -> blob for nim files
 */
async function prefetchVendor() {
  const total = VENDOR_FILES.reduce((acc, f) => acc + f.size, 0);
  let done = 0;
  progressWrap.classList.add('visible');
  const update = (label) => {
    const pct = Math.min(100, (done / total) * 100);
    progressBar.style.width = `${pct}%`;
    progressLabel.textContent =
      `Downloading the compiler (first visit only)… ${mb(done)} of about ${mb(total)} MB — ${label}`;
  };

  const preloaded = new Map();
  update('starting');
  for (const file of VENDOR_FILES) {
    update(file.label);
    const blob = await prefetchFile(file, (n) => {
      done += n;
      update(file.label);
    });
    if (blob && file.path.startsWith('nim/')) {
      preloaded.set(file.path.slice('nim/'.length), blob);
    }
  }
  progressBar.style.width = '100%';
  progressWrap.classList.remove('visible');
  return preloaded;
}

/* --------------------------------------------------------------------------
 * Toolchains + run flow.
 * ------------------------------------------------------------------------ */

let nim = null;
let clang = null;

/**
 * Map a pipeline result to a one-line plain-English summary plus the raw
 * compiler output for the collapsible details (SPEC §8c).
 *
 * @param {{stage: string, error?: string, nimStdout: string,
 *   nimStderr: string, clangLog: string}} result
 * @returns {{summary: string, raw: string}}
 */
function friendlyError(result) {
  const raw = [
    result.error || '',
    result.nimStderr || '',
    result.nimStdout || '',
    result.clangLog || '',
  ].filter((s) => s && s.trim()).join('\n\n');

  if (result.stage === 'nim') {
    // Typical Nim error: "/project/main.nim(4, 10) Error: undeclared identifier: 'foo'"
    const m = /main\.nim\((\d+),\s*\d+\)\s*Error:\s*(.+)/.exec(result.nimStderr || '');
    if (m) {
      return { summary: `The Nim compiler didn't understand line ${m[1]}: ${m[2]}`, raw };
    }
    return { summary: "The Nim compiler couldn't understand your code. Details below.", raw };
  }
  if (result.stage === 'clang') {
    return { summary: 'The C build step reported a problem. Details below.', raw };
  }
  return { summary: `Your app was built, but it failed to start: ${result.error || 'unknown error'}`, raw };
}

/**
 * Load both toolchains in parallel after the one-time download; enable
 * the run button when ready.
 */
async function init() {
  setStatus('Loading compiler (first visit downloads about 75 MB)…', 'busy');
  try {
    const preloaded = await prefetchVendor();
    setStatus('Starting the compiler…', 'busy');
    nim = new NimCompiler({
      vendorUrl: config.vendorUrl,
      libpacksUrl: config.libpacksUrl,
      onLog: log,
      preloaded,
    });
    clang = new ClangCompiler({ vendorUrl: config.vendorUrl, onLog: log });
    await Promise.all([nim.init(), clang.init()]);
    setStatus('Ready — press Run', 'ok');
    log('ready — press Run to build and run your program', 'ok');
    runBtn.disabled = false;
  } catch (e) {
    setStatus('The compiler failed to load', 'err');
    log(`initialization failed: ${e.message || e}`, 'error');
    showError(
      'The compiler could not be loaded. Check your internet connection and reload the page.',
      `initialization failed: ${e.message || e}\n\nexpected layout: ./vendor/nim/*, ./vendor/clang/*, ./libpacks/manifest.json next to index.html`
    );
  }
}

runBtn.addEventListener('click', async () => {
  runBtn.disabled = true;
  consoleEl.innerHTML = '';
  outputEl.innerHTML = '';
  hideError();
  const t0 = performance.now();
  try {
    const result = await compileAndRun({
      source: editor.value,
      nim,
      clang,
      runtime: { createBindwebRunner },
      outputEl,
      onLog: (msg, kind) => {
        log(msg, kind);
        // Plain-English status narration for each pipeline stage (SPEC §8c).
        if (kind === 'step') {
          if (msg.includes('step 1')) setStatus('Translating Nim to C…', 'busy');
          else if (msg.includes('step 2')) setStatus('Preparing the C code…', 'busy');
          else if (msg.includes('step 3')) setStatus('Compiling C to WebAssembly…', 'busy');
          else if (msg.includes('step 4')) setStatus('Running your app…', 'busy');
        }
      },
    });
    const dt = ((performance.now() - t0) / 1000).toFixed(1);
    if (result.ok) {
      setStatus(`Running — done in ${dt}s`, 'ok');
    } else {
      const { summary, raw } = friendlyError(result);
      setStatus('Something went wrong — see the message below', 'err');
      showError(summary, raw);
      log(summary, 'error');
    }
  } catch (e) {
    setStatus('Something went wrong — see the message below', 'err');
    showError('The build stopped unexpectedly. Details below.', e.stack || String(e));
    log(`pipeline error: ${e.message || e}`, 'error');
  } finally {
    runBtn.disabled = false;
  }
});

editor.value = EXAMPLES[0].source;
updateLineNumbers();
init();
