/**
 * main.js — UI glue for the nim-wasm-compiler IDE (SPEC §8c:
 * non-programmer-friendly, one big Run button, examples, honest
 * download progress, friendly errors).
 *
 * Wires the editor, console log pane and app output pane to the compile
 * pipeline (web/src/pipeline.js). No frameworks, no bundler: plain ES
 * modules loaded via <script type="module">.
 *
 * Served from the dist root (tools/make-dist.sh copies web/ to dist/), so
 * vendor/ and libpacks/ are sibling directories — see `config` below.
 *
 * Download progress: the big vendor wasm files are fetched ONCE here with
 * a ReadableStream reader so the byte count (and MB label) is real. The
 * fetched nim.wasm / nim-bundle.data bytes are handed to the Nim compiler
 * as blob: URLs through its `preloaded` option, so those are never
 * downloaded twice. The clang worker re-fetches its own files by URL
 * inside a Web Worker (no way to hand it blobs from here); on a served
 * dist the browser HTTP cache normally makes that second read free.
 */

import { NimCompiler } from './nim-compiler.js';
import { ClangCompiler } from './clang-compiler.js';
import { compileAndRun, compileToWasm } from './pipeline.js';
import { createBindwebRunner } from './runtime/bindweb-browser-runtime.js';
import { listLibs, getLibsWithFiles, deleteLib, slugify } from './libstore.js';
import { importFromGitHub, importFromZipFile, fetchRegistry, normalizeGitUrl, parseGitHubUrl } from './libimport.js';
import {
  AREA_WORKSPACE, AREA_SITE,
  listFiles, readFile, writeFile, makeDir, deletePath, renamePath, clearArea,
  getFilesWithData, baseName, isLikelyBinary,
} from './vfs.js';
import {
  SITE_GENERATED_MARKER, RUNTIME_SITE_FILES, SITE_BOOT_JS,
  stripEsmExports, rewriteSiteUrls, disarmDomainGateForPreview, mimeFor,
  generateSiteIndex, collectBoundDomains,
} from './site-template.js';
import { zipFiles } from './zip.js';
import { installNimIDE } from './ai-api.js';

/**
 * Dist-layout config: index.html sits at the dist root next to vendor/
 * (populated by build.sh) and libpacks/ (generated by tools/pack-lib.sh).
 */
const config = { vendorUrl: './vendor', libpacksUrl: './libpacks' };

/**
 * The big toolchain files, with their known sizes in bytes (measured on the
 * pinned clang.js@0.1.1 npm artifacts + nim.wasm build; used only as the
 * progress-bar denominator — actual bytes are counted as they stream in, so
 * a rebuilt nim.wasm with a different size is fine). Total is about 73 MB.
 */
const VENDOR_FILES = [
  { path: 'clang/clang.wasm', size: 31214472, label: 'C compiler' },
  { path: 'clang/lld.wasm', size: 19490094, label: 'linker' },
  { path: 'clang/sysroot.tar', size: 9297920, label: 'C library' },
  { path: 'clang/memfs.wasm', size: 345442, label: 'C library helper' },
  { path: 'clang/clang.js', size: 19214, label: 'C compiler glue' },
  { path: 'nim/nim.wasm', size: 4812366, label: 'Nim compiler' },
  { path: 'nim/nim-bundle.js', size: 6566418, label: 'Nim compiler glue' },
  // NOTE: no nim-bundle.data — this build ships the stdlib/config as libpacks
  // (mounted into MEMFS at run time), and emcc is invoked without --preload-file,
  // so no .data blob is produced. Prefetching it only yielded a harmless 404.
];

/* --------------------------------------------------------------------------
 * Example programs. Written against the bindweb APIs (see Bindweb/examples
 * and the generated apis/*.nim). Nim identifiers are style-insensitive after
 * the first character, so camelCase calls map to the snake_case definitions.
 * ------------------------------------------------------------------------ */

const EXAMPLE_BUTTONS = `## Buttons -- JS event + Nim closure (WebApp).
## Button 1 is wired with raw JavaScript via inject_script.
## Button 2 is wired with a real Nim callback that captures a local,
## which is what the WebApp event system needs on the WASM backend.

import bindweb, bindwebtypes, bindwebevents
import apis/handles, apis/dom, apis/system

proc main() =
  let body = getBody()

  let container = createElement("div")
  setAttribute(container, "style", "padding:24px; max-width:640px; margin:0 auto; font-family:sans-serif;")
  appendChild(body, container)

  let title = createElement("h1")
  setAttribute(title, "style", "color:#e6edf3;")
  setInnerText(title, "Nim Bindweb DOM Demo")
  appendChild(container, title)

  let subtitle = createElement("p")
  setAttribute(subtitle, "style", "color:#9aa4af; margin-bottom:16px;")
  setInnerText(subtitle, "Button 1 runs JavaScript. Button 2 fires a Nim callback via WebApp.")
  appendChild(container, subtitle)

  # --- Button 1: pure JavaScript via inject_script + addEventListener ---

  let jsBtn = createElement("button")
  setAttribute(jsBtn, "id", "js-color-btn")
  setAttribute(jsBtn, "style", "padding:12px 24px; background:#2196F3; color:#fff; border:none; border-radius:6px; cursor:pointer; font-size:16px; margin-right:8px;")
  setInnerText(jsBtn, "JS: Change Color")
  appendChild(container, jsBtn)

  inject_script("""

    document.getElementById('js-color-btn').addEventListener('click', function(e) {

      e.currentTarget.style.background = '#' + Math.floor(Math.random() * 16777215).toString(16);

    });

  """)

  # --- Button 2: Nim callback via WebApp event system ---

  let nimBtn = createElement("button")
  setAttribute(nimBtn, "style", "padding:12px 24px; background:#4CAF50; color:#fff; border:none; border-radius:6px; cursor:pointer; font-size:16px;")
  setInnerText(nimBtn, "Nim: Click Me!")
  appendChild(container, nimBtn)

  addClickListener(nimBtn)

  let nimResult = createElement("div")
  setAttribute(nimResult, "style", "margin-top:14px; padding:12px; background:#0f2417; border:1px solid #2e7d32; border-radius:6px; color:#7ee787;")
  setInnerText(nimResult, "Status: click the green button - WebApp will dispatch to onClick.")
  appendChild(container, nimResult)

  setTitle("Nim Bindweb DOM Demo")
  flush()

  # --- High-level WebApp event system. clickCount + nimResult are LOCALS, so
  # this handler captures them -> it is a real closure (env != nil), which is the
  # calling convention the dispatcher (and the WASM backend) handle correctly. ---

  let app = newWebApp()
  var clickCount = 0
  app.onClick = proc(ev: ClickEvent) =
    clickCount += 1
    setInnerText(nimResult,
      "Nim handled click #" & $clickCount & " via WebApp.onClick  (handle " & $ev.handle.int32 & ")")
    log("Click event dispatched: Click")
    flush()
  app.run()

main()
`;

const EXAMPLE_ROTATE = `## Rotating canvas -- a 60 FPS animated Canvas 2D scene.
## Uses setMainLoop with a top-level update proc; the rotation state is a
## module-level var so the proc can mutate it on every frame.

import bindweb, bindwebtypes

import apis/handles, apis/dom, apis/canvas, apis/system

var
  ctx: CanvasContext2DHandle
  rotation = 0.0

proc update(timeMs: float64) =
  # Clear and draw rotating rectangle
  setFillStyle(ctx, 30, 30, 50)
  fillRect(ctx, 0, 0, 600, 400)

  # Save context
  save(ctx)

  # Translate to center and rotate
  translate(ctx, 300.0, 200.0)
  rotate(ctx, rotation)

  # Draw colored square
  setFillStyle(ctx, 100, 200, 255)
  fillRect(ctx, -50.0, -50.0, 100.0, 100.0)

  # Draw inner square
  setFillStyle(ctx, 255, 100, 150)
  fillRect(ctx, -25.0, -25.0, 50.0, 50.0)

  restore(ctx)

  # Draw title text
  setFont(ctx, "20px Arial")
  setFillStyle(ctx, 255, 255, 255)
  fillText(ctx, "Canvas Demo from Nim!", 180.0, 30.0)

  setFont(ctx, "14px Arial")
  setFillStyle(ctx, 200, 200, 200)
  fillText(ctx, "Rotating squares with Canvas 2D", 190.0, 55.0)

  # Update rotation
  rotation += 0.02

  flush()

proc main() =
  let body = getBody()

  # Create canvas
  let canvas = createCanvas("demo-canvas", 600.0, 400.0)
  appendChild(body, canvas)

  # Get 2D context
  ctx = getContext2d(canvas)

  # Start animation loop
  setMainLoop(update)

  flush()

main()
`;

const EXAMPLE_MOUSE = `## Mouse interaction -- draw a glowing dot that follows the mouse.
## All interaction state lives as LOCALS captured by the WebApp handlers, so
## each handler is a real closure with a uniform signature (the WASM backend
## needs this: a non-capturing handler gets a different function-table
## signature and dispatching a struct event through it throws
## "function signature mismatch").

import bindweb, bindwebtypes, bindwebevents

import apis/handles, apis/dom, apis/canvas, apis/system, apis/input

proc main() =
  var
    ctx: CanvasContext2DHandle
    mouseX = 300
    mouseY = 200
    isClicking = false

  let body = getBody()
  let canvas = createCanvas("mouse-canvas", 600.0, 400.0)
  appendChild(body, canvas)
  ctx = getContext2d(canvas)
  initMouse(canvas)

  # Nested so it captures the same locals the handlers mutate.
  proc drawFrame() =
    setFillStyle(ctx, 20, 20, 35)
    fillRect(ctx, 0, 0, 600, 400)

    setStrokeStyleStr(ctx, "#333")
    setLineWidth(ctx, 1.0)
    for i in 0..<10:
      let x = float64(i * 60)
      beginPath(ctx)
      moveTo(ctx, x, 0.0)
      lineTo(ctx, x, 400.0)
      stroke(ctx)
      let y = float64(i * 40)
      beginPath(ctx)
      moveTo(ctx, 0.0, y)
      lineTo(ctx, 600.0, y)
      stroke(ctx)

    beginPath(ctx)
    arc(ctx, float64(mouseX), float64(mouseY), 30.0, 0.0, 6.28318)
    if isClicking:
      setFillStyle(ctx, 255, 80, 80)
      setShadow(ctx, 20.0, 0.0, 0.0, "red")
    else:
      setFillStyle(ctx, 80, 255, 120)
      setShadow(ctx, 10.0, 5.0, 5.0, "rgba(0,0,0,0.5)")
    fill(ctx)

    setStrokeStyleStr(ctx, "rgba(255,255,255,0.3)")
    setLineWidth(ctx, 1.0)
    beginPath(ctx)
    moveTo(ctx, float64(mouseX) - 40.0, float64(mouseY))
    lineTo(ctx, float64(mouseX) + 40.0, float64(mouseY))
    stroke(ctx)
    beginPath(ctx)
    moveTo(ctx, float64(mouseX), float64(mouseY) - 40.0)
    lineTo(ctx, float64(mouseX), float64(mouseY) + 40.0)
    stroke(ctx)

    setFont(ctx, "16px monospace")
    setFillStyle(ctx, 255, 255, 255)
    fillText(ctx, "Mouse: (" & $mouseX & ", " & $mouseY & ")", 10.0, 25.0)
    if isClicking:
      fillText(ctx, "CLICKING!", 10.0, 50.0)
    flush()

  let app = newWebApp()
  app.onMouseMove = proc(ev: MouseMoveEvent) =
    mouseX = ev.x
    mouseY = ev.y
  app.onMouseDown = proc(ev: MouseDownEvent) =
    isClicking = true
  app.onMouseUp = proc(ev: MouseUpEvent) =
    isClicking = false

  setTitle("Nim Bindweb Mouse Input Demo")
  app.webloop:
    drawFrame()

main()
`;

const EXAMPLE_HASH = `## Hashing -- uses the nim-lang/checksums library added in the Libraries tab.
## Open the Libraries tab, add https://github.com/nim-lang/checksums,
## then press Run. (Until you do, this fails with "cannot open file: checksums/sha2".)

import checksums/sha2, checksums/md5

proc main() =
  let text = "Hello from Nim in the browser!"
  echo "input:   ", text
  echo "SHA-256: ", $Sha_256.secureHash(text)
  echo "SHA-512: ", $Sha_512.secureHash(text)
  echo "MD5:     ", getMD5(text)

main()
`;

const EXAMPLES = [
  { id: 'buttons', label: 'Buttons (JS + WebApp)', source: EXAMPLE_BUTTONS },
  { id: 'rotate', label: 'Rotating Canvas', source: EXAMPLE_ROTATE },
  { id: 'mouse', label: 'Mouse Interaction', source: EXAMPLE_MOUSE },
  {
    id: 'hash', label: 'Hashing (Libraries tab demo)', source: EXAMPLE_HASH,
    libId: 'checksums', libUrl: 'https://github.com/nim-lang/checksums',
  },
];

/* --------------------------------------------------------------------------
 * DOM handles + small UI helpers.
 * ------------------------------------------------------------------------ */

const editor = document.getElementById('editor');
const lineNumbers = document.getElementById('line-numbers');
const consoleEl = document.getElementById('console');
const outputEl = document.getElementById('app-output');
const statusEl = document.getElementById('status');
const runBtn = document.getElementById('btn-run');
const buildBtn = document.getElementById('btn-build');
const examplesEl = document.getElementById('examples');
const progressWrap = document.getElementById('progress-wrap');
const progressBar = document.getElementById('progress-bar');
const progressLabel = document.getElementById('progress-label');
const errorBox = document.getElementById('error-box');
const errorSummary = document.getElementById('error-summary');
const errorRaw = document.getElementById('error-raw');

/**
 * Update the status pill.
 *
 * @param {string} text status message
 * @param {'' | 'busy' | 'ok' | 'err'} [kind] visual state
 */
function setStatus(text, kind = '') {
  statusEl.textContent = text;
  statusEl.className = kind;
}

/**
 * Log tap: listeners registered here receive every (msg, kind) pair that
 * log() writes to the console pane. The window.NimIDE API (ai-api.js) uses
 * it to capture a build's log lines without scraping the DOM.
 *
 * @type {Set<(msg: string, kind: string) => void>}
 */
const logListeners = new Set();

/**
 * Register a log listener; returns an unregister function. Listener
 * exceptions are swallowed so a broken tap can never break the UI.
 */
function addLogListener(fn) {
  logListeners.add(fn);
  return () => logListeners.delete(fn);
}

/**
 * Append a line to the console pane.
 *
 * @param {string} msg message text
 * @param {string} [kind] 'step' | 'info' | 'ok' | 'warn' | 'error' |
 *   'stdout' | 'stderr'
 */
function log(msg, kind = 'info') {
  const line = document.createElement('div');
  line.className = `line ${kind}`;
  const stamp = document.createElement('span');
  stamp.className = 't';
  stamp.textContent = new Date().toLocaleTimeString('en-GB', { hour12: false });
  line.appendChild(stamp);
  line.appendChild(document.createTextNode(msg));
  consoleEl.appendChild(line);
  consoleEl.scrollTop = consoleEl.scrollHeight;
  for (const fn of logListeners) {
    try { fn(msg, kind); } catch (e) { /* a broken tap must not break logging */ }
  }
}

/** Show the friendly error box (SPEC §8c: never alert()). */
function showError(summary, raw) {
  errorSummary.textContent = summary;
  errorRaw.textContent = raw && raw.trim() ? raw.trim() : '(no further output)';
  errorBox.classList.add('visible');
}

/** Hide the friendly error box (on each new run). */
function hideError() {
  errorBox.classList.remove('visible');
}

/** Refresh the line-number gutter to match the editor content. */
function updateLineNumbers() {
  const count = editor.value.split('\n').length;
  const nums = new Array(count);
  for (let i = 0; i < count; i++) nums[i] = i + 1;
  lineNumbers.textContent = nums.join('\n');
  lineNumbers.scrollTop = editor.scrollTop;
}

editor.addEventListener('input', updateLineNumbers);
// Auto-save the open file into the workspace store (debounced).
editor.addEventListener('input', scheduleSave);
editor.addEventListener('scroll', () => {
  lineNumbers.scrollTop = editor.scrollTop;
});
editor.addEventListener('keydown', (e) => {
  if (e.key === 'Tab') {
    e.preventDefault();
    const { selectionStart: start, selectionEnd: end } = editor;
    editor.setRangeText('  ', start, end, 'end');
    updateLineNumbers();
  }
});

/* --------------------------------------------------------------------------
 * Examples dropdown.
 * ------------------------------------------------------------------------ */

for (const ex of EXAMPLES) {
  const opt = document.createElement('option');
  opt.value = ex.id;
  opt.textContent = ex.label;
  examplesEl.appendChild(opt);
}
examplesEl.disabled = false;

examplesEl.addEventListener('change', async () => {
  const ex = EXAMPLES.find((e) => e.id === examplesEl.value);
  if (!ex) return;
  // Examples become real files in the working folder (examples/<id>.nim),
  // so they can be edited, built and kept like any other project file.
  const path = `examples/${ex.id}.nim`;
  try {
    await writeFile(AREA_WORKSPACE, path, ex.source);
    await openFile(path);
    log(`loaded example "${ex.label}" into ${path} — press Run to try it`, 'info');
  } catch (e) {
    // Store unavailable: fall back to session-only editing.
    editor.value = ex.source;
    updateLineNumbers();
    log(`loaded example "${ex.label}" (file store unavailable — not saved)`, 'warn');
  }
  hideError();
  // Examples that need a user library: jump to the Libraries tab only when
  // the library is not installed yet.
  if (ex.libId) {
    try {
      const libs = await listLibs();
      if (!libs.some((l) => l.id === ex.libId)) {
        log(`this example needs ${ex.libId} — add it in the Libraries tab (link is pre-filled)`, 'warn');
        if (ex.libUrl) libUrlEl.value = ex.libUrl;
        showTab('libs');
      }
    } catch (e) { /* store unavailable: the compile error will say what to do */ }
  }
});

/* --------------------------------------------------------------------------
 * Libraries sub-tab: install Nim libraries from a GitHub link or a .zip
 * upload into IndexedDB; they mount at /libs/<name> on the next Run.
 * ------------------------------------------------------------------------ */

const tabCode = document.getElementById('tab-code');
const tabProject = document.getElementById('tab-project');
const tabSite = document.getElementById('tab-site');
const tabLibs = document.getElementById('tab-libs');
const codeView = document.getElementById('code-view');
const projectView = document.getElementById('project-view');
const siteView = document.getElementById('site-view');
const libsView = document.getElementById('libs-view');
const libCountEl = document.getElementById('lib-count');
const libUrlEl = document.getElementById('lib-url');
const libAddBtn = document.getElementById('lib-add');
const libUploadBtn = document.getElementById('lib-upload-btn');
const libUploadEl = document.getElementById('lib-upload');
const libUploadName = document.getElementById('lib-upload-name');
const libStatusEl = document.getElementById('lib-status');
const libListEl = document.getElementById('lib-list');

/**
 * Switch between the four left-pane sub-tabs: Code (the editor), Project
 * (the Nim working folder), Site (the deployed static webpage folder) and
 * Libraries.
 *
 * @param {'code' | 'project' | 'site' | 'libs'} which
 */
function showTab(which) {
  tabCode.classList.toggle('active', which === 'code');
  tabProject.classList.toggle('active', which === 'project');
  tabSite.classList.toggle('active', which === 'site');
  tabLibs.classList.toggle('active', which === 'libs');
  codeView.hidden = which !== 'code';
  projectView.hidden = which !== 'project';
  siteView.hidden = which !== 'site';
  libsView.hidden = which !== 'libs';
  if (which === 'libs') renderLibList();
  if (which === 'project') renderWorkspaceTree();
  if (which === 'site') renderSiteTree();
}

tabCode.addEventListener('click', () => showTab('code'));
tabProject.addEventListener('click', () => showTab('project'));
tabSite.addEventListener('click', () => showTab('site'));
tabLibs.addEventListener('click', () => showTab('libs'));

/**
 * One-line status inside the Libraries panel.
 *
 * @param {string} msg
 * @param {'busy' | 'ok' | 'err'} kind
 */
function libStatus(msg, kind) {
  libStatusEl.textContent = msg;
  libStatusEl.className = `visible ${kind}`;
}

/** Format a byte count compactly for the list rows. */
function fmtBytes(n) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(2)} MB`;
}

/** Re-render the installed-libraries list from IndexedDB. */
async function renderLibList() {
  let libs = [];
  try {
    libs = await listLibs();
  } catch (e) {
    libListEl.innerHTML = '';
    const div = document.createElement('div');
    div.id = 'lib-empty';
    div.textContent = `The library store is unavailable: ${e.message || e}`;
    libListEl.appendChild(div);
    return;
  }
  libCountEl.textContent = libs.length > 0 ? String(libs.length) : '';
  libListEl.innerHTML = '';

  if (libs.length === 0) {
    const div = document.createElement('div');
    div.id = 'lib-empty';
    div.textContent = 'No libraries yet — add one from a GitHub link or a .zip above.';
    libListEl.appendChild(div);
    return;
  }

  for (const lib of libs) {
    const item = document.createElement('div');
    item.className = 'lib-item';

    const main = document.createElement('div');
    main.className = 'lib-item-main';

    const name = document.createElement('div');
    name.className = 'lib-item-name';
    name.textContent = lib.name;
    const mount = document.createElement('span');
    mount.className = 'lib-mount';
    mount.textContent = lib.mount;
    name.appendChild(mount);
    main.appendChild(name);

    const meta = document.createElement('div');
    meta.className = 'lib-item-meta';
    const when = new Date(lib.addedAt).toLocaleString();
    if (lib.source && lib.source.kind === 'github' && lib.source.url) {
      const a = document.createElement('a');
      a.href = lib.source.url;
      a.target = '_blank';
      a.rel = 'noopener';
      a.textContent = lib.source.url.replace(/^https?:\/\//, '');
      meta.appendChild(a);
      meta.appendChild(document.createTextNode(
        `${lib.source.ref ? ` @ ${lib.source.ref}` : ''} · added ${when} · `));
    } else {
      meta.textContent = `zip upload${lib.source && lib.source.filename ? ` (${lib.source.filename})` : ''} · added ${when} · `;
    }
    meta.appendChild(document.createTextNode(`${lib.fileCount} files · ${fmtBytes(lib.totalBytes)}`));
    if (lib.source && lib.source.via) {
      meta.appendChild(document.createTextNode(` · via ${lib.source.via}`));
    }
    main.appendChild(meta);

    if (lib.requires && lib.requires.length > 0) {
      const req = document.createElement('div');
      req.className = 'lib-item-requires';
      req.textContent = `nimble requires: ${lib.requires.join(', ')}`;
      main.appendChild(req);
    }

    const remove = document.createElement('button');
    remove.className = 'lib-remove';
    remove.type = 'button';
    remove.textContent = 'Remove';
    remove.addEventListener('click', async () => {
      try {
        await deleteLib(lib.id);
        log(`libraries: removed "${lib.name}" (applies on next Run)`, 'info');
        renderLibList();
      } catch (e) {
        libStatus(`Could not remove ${lib.name}: ${e.message || e}`, 'err');
      }
    });

    item.appendChild(main);
    if (lib.requires && lib.requires.length > 0) {
      const deps = document.createElement('button');
      deps.className = 'lib-remove';
      deps.style.color = 'var(--accent)';
      deps.type = 'button';
      deps.textContent = 'Deps…';
      deps.title = 'Check / install missing dependencies';
      deps.addEventListener('click', () => offerDependencies(lib));
      item.appendChild(deps);
    }
    item.appendChild(remove);
    libListEl.appendChild(item);
  }
}

/** Shared busy/ok flow for the two add paths. */
async function addLibrary(kind, payload) {
  libAddBtn.disabled = true;
  libUploadBtn.disabled = true;
  try {
    const lib = kind === 'github'
      ? await importFromGitHub(payload, (m) => libStatus(m, 'busy'))
      : await importFromZipFile(payload, (m) => libStatus(m, 'busy'));
    libStatus(
      `Added "${lib.name}" — ${lib.fileCount} files at ${lib.mount}. ` +
      'Press Run to compile against it.',
      'ok'
    );
    log(`libraries: added "${lib.name}" at ${lib.mount} (${lib.fileCount} files)`, 'ok');
    libUrlEl.value = '';
    libUploadName.textContent = '';
    await renderLibList();
    // Dependencies come last so the dialog opens on a settled list.
    offerDependencies(lib);
  } catch (e) {
    libStatus(e.message || String(e), 'err');
    log(`libraries: add failed: ${e.message || e}`, 'error');
  } finally {
    libAddBtn.disabled = false;
    libUploadBtn.disabled = false;
  }
}

/* --------------------------------------------------------------------------
 * Dependency resolution: after a library is added, its .nimble requirements
 * are resolved against the official nimble registry and offered in a dialog;
 * confirmed packages install recursively (each shows up in the list with a
 * "via <parent>" note, so it can be checked and removed like any other).
 * ------------------------------------------------------------------------ */

const depModal = document.getElementById('dep-modal');
const depSub = document.getElementById('dep-sub');
const depList = document.getElementById('dep-list');
const depInstallBtn = document.getElementById('dep-install');
const depSkipBtn = document.getElementById('dep-skip');

/**
 * Dialog state. Rows: Map key -> {name, via, statusEl, approved, settled}.
 * `approved` = the user explicitly confirmed this row (nothing installs
 * without it). `settled` = installed / failed / declined — no longer
 * actionable. Queue holds keys approved and waiting to install.
 *
 * @type {null | {rows: Map<string, object>, queue: string[], session: number,
 *   registry: object|null, installedNow: object[]}}
 */
let depState = null;
let depSessionCounter = 0;

/** True when an installed record provides nimble package `key` (lowercase). */
function libProvides(libs, key) {
  return libs.some(
    (l) => (l.pkgName && l.pkgName.toLowerCase() === key) || l.id === slugify(key)
  );
}

/**
 * Open the dependency dialog for a library, listing the requirements that
 * are not installed yet. NOTHING installs until the user confirms; any
 * transitive dependencies discovered while installing are held in the same
 * dialog for a fresh approval round (never installed silently).
 *
 * @param {object} lib stored library metadata (requires: string[])
 */
async function offerDependencies(lib) {
  const names = [...new Set(
    (lib.requires || []).map((n) => n.trim()).filter((n) => n && n.toLowerCase() !== 'nim')
  )];
  if (names.length === 0) return;

  let installed = [];
  try { installed = await listLibs(); } catch (e) { /* empty store is fine */ }
  const missing = names.filter((n) => !libProvides(installed, n.toLowerCase()));
  if (missing.length === 0) {
    log(`libraries: all dependencies of "${lib.name}" are already installed`, 'info');
    return;
  }

  const session = ++depSessionCounter;
  depState = { rows: new Map(), queue: [], session, registry: null, installedNow: installed };
  depList.innerHTML = '';
  depModal.classList.add('visible');
  depModal.setAttribute('aria-hidden', 'false');
  for (const name of missing) enqueueDep(name, lib.name);
  enterApprovalMode(
    `"${lib.name}" needs ${missing.length === 1 ? 'this package' : 'these packages'} ` +
    '(from its .nimble file). Review them — nothing is installed until you confirm.'
  );
}

/** Add one row to the dialog; the row starts unapproved (needs a click). */
function enqueueDep(name, via) {
  const key = name.toLowerCase();
  if (!depState || depState.rows.has(key)) return;
  if (libProvides(depState.installedNow, key)) return; // already there: no row
  const row = document.createElement('div');
  row.className = 'dep-row';
  const nameEl = document.createElement('div');
  nameEl.className = 'dep-row-name';
  nameEl.textContent = name;
  const viaEl = document.createElement('span');
  viaEl.className = 'dep-via';
  viaEl.textContent = ` (via ${via})`;
  nameEl.appendChild(viaEl);
  const statusEl = document.createElement('div');
  statusEl.className = 'dep-row-status';
  row.appendChild(nameEl);
  row.appendChild(statusEl);
  depList.appendChild(row);
  depState.rows.set(key, { name, via, statusEl, approved: false, settled: false });
  setDepStatus(key, 'needs approval', '');
}

function setDepStatus(key, state, detail) {
  const entry = depState && depState.rows.get(key);
  if (!entry) return;
  const cls = state === 'installing' || state === 'looking up' || state === 'needs approval' ? 'busy'
    : state === 'installed' || state === 'already installed' ? 'ok'
    : state === 'declined' ? 'warn'
    : state === 'failed' ? 'err' : '';
  entry.statusEl.className = `dep-row-status ${cls}`;
  entry.statusEl.textContent = detail ? `${state} — ${detail}` : state;
}

/** Rows the user has not approved yet and that are not settled. */
function pendingDepRows() {
  return [...depState.rows.entries()].filter(([, r]) => !r.settled && !r.approved);
}

/** Put the dialog into "waiting for the user's decision" mode. */
function enterApprovalMode(subText) {
  const pending = pendingDepRows();
  depSub.textContent = subText;
  depInstallBtn.textContent = pending.length === 1
    ? 'Install 1 package'
    : `Install ${pending.length} packages`;
  depInstallBtn.disabled = pending.length === 0;
  depSkipBtn.textContent = 'Decline';
  depSkipBtn.disabled = false;
}

/** Put the dialog into its finished state (summary + Close). */
function enterDoneMode() {
  const rows = [...depState.rows.values()];
  const failed = rows.filter((r) => r.statusEl.className.includes('err')).length;
  const declined = rows.filter((r) => r.statusEl.className.includes('warn')).length;
  if (declined > 0) {
    depSub.textContent =
      `Kept the installed packages; ${declined} package(s) were declined. ` +
      'The compile may fail until you add them (Deps… button re-opens this).';
  } else if (failed > 0) {
    depSub.textContent =
      `Done, but ${failed} package(s) could not be installed — add those manually (GitHub link or .zip).`;
  } else {
    depSub.textContent = 'All dependencies installed. Press Run to compile.';
  }
  depInstallBtn.textContent = 'Close';
  depInstallBtn.disabled = false;
  depSkipBtn.textContent = 'Close';
  depSkipBtn.disabled = false;
}

function closeDepDialog() {
  depModal.classList.remove('visible');
  depModal.setAttribute('aria-hidden', 'true');
  depSessionCounter++; // invalidate any in-flight install loop
  depState = null;
}

depSkipBtn.addEventListener('click', () => {
  if (!depState) { closeDepDialog(); return; }
  if (depSkipBtn.textContent === 'Close') { closeDepDialog(); return; }
  const anySettled = [...depState.rows.values()].some((r) => r.settled);
  if (!anySettled) { closeDepDialog(); return; } // nothing installed yet: just bail
  // Decline everything still pending — keep what is already installed.
  for (const [key, r] of pendingDepRows()) {
    r.settled = true;
    setDepStatus(key, 'declined', 'kept out');
    log(`libraries: dependency "${r.name}" declined by user`, 'info');
  }
  enterDoneMode();
});
depModal.querySelector('.dep-backdrop').addEventListener('click', () => {
  if (depSkipBtn.disabled) return; // don't close mid-install by accident
  closeDepDialog();
});

depInstallBtn.addEventListener('click', async () => {
  if (!depState) { closeDepDialog(); return; }
  if (depInstallBtn.textContent === 'Close') { closeDepDialog(); return; }

  // Approve everything currently pending: it joins the install queue.
  const pending = pendingDepRows();
  if (pending.length === 0) return;
  for (const [key, r] of pending) {
    r.approved = true;
    depState.queue.push(key);
    setDepStatus(key, 'queued', '');
  }
  const session = depState.session;
  depInstallBtn.disabled = true;
  depSkipBtn.disabled = true;

  if (!depState.registry) {
    try {
      depState.registry = await fetchRegistry();
    } catch (e) {
      depState.registry = null;
    }
  }
  const registry = depState.registry;

  let guard = 0;
  while (depState && depState.session === session && depState.queue.length > 0 && guard++ < 50) {
    const key = depState.queue.shift();
    const entry = depState.rows.get(key);
    if (!entry || entry.settled) continue;

    if (libProvides(depState.installedNow, key)) {
      entry.settled = true;
      setDepStatus(key, 'already installed', '');
      continue;
    }
    const pkg = registry ? registry.get(key) : null;
    let parsed = null;
    if (pkg) {
      try { parsed = parseGitHubUrl(normalizeGitUrl(pkg.url)); } catch (e) { parsed = null; }
    }
    if (!parsed) {
      entry.settled = true;
      setDepStatus(key, 'failed', registry
        ? (pkg ? 'not on github.com — add manually' : 'not in the nimble registry — add manually')
        : 'nimble registry unavailable');
      continue;
    }

    setDepStatus(key, 'looking up', `${parsed.owner}/${parsed.repo}`);
    try {
      const meta = await importFromGitHub(normalizeGitUrl(pkg.url), () => {}, { via: entry.via });
      entry.settled = true;
      setDepStatus(key, 'installed', `${meta.fileCount} files at ${meta.mount}`);
      log(`libraries: installed dependency "${meta.name}" (via ${entry.via}) at ${meta.mount}`, 'ok');
      depState.installedNow.push(meta);
      renderLibList();
      // Transitive deps: list them for a NEW approval round — never install
      // anything the user has not seen and confirmed.
      for (const depName of meta.requires || []) {
        if (depName.toLowerCase() === 'nim') continue;
        enqueueDep(depName, meta.name);
      }
    } catch (e) {
      entry.settled = true;
      setDepStatus(key, 'failed', e.message || 'download failed');
      log(`libraries: dependency "${entry.name}" failed: ${e.message || e}`, 'warn');
    }
  }

  if (!depState || depState.session !== session) return;
  const stillPending = pendingDepRows();
  if (stillPending.length > 0) {
    // Round complete, new deps discovered: ask again before continuing.
    enterApprovalMode(
      `${stillPending.length === 1 ? 'One more package is' : `${stillPending.length} more packages are`} ` +
      'required by the ones above. Review and install? (Declined packages are kept out.)'
    );
  } else {
    enterDoneMode();
  }
});

libAddBtn.addEventListener('click', () => {
  const url = libUrlEl.value.trim();
  if (!url) {
    libStatus('Paste a GitHub repository link first.', 'err');
    return;
  }
  addLibrary('github', url);
});
libUrlEl.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') libAddBtn.click();
});

libUploadBtn.addEventListener('click', () => libUploadEl.click());
libUploadEl.addEventListener('change', () => {
  const file = libUploadEl.files && libUploadEl.files[0];
  libUploadEl.value = ''; // allow re-picking the same file
  if (!file) return;
  libUploadName.textContent = file.name;
  addLibrary('zip', file);
});

// Keep the badge honest from the start (IndexedDB survives reloads).
renderLibList();

/* --------------------------------------------------------------------------
 * Virtual folders (vfs.js): the Project tab is the Nim working folder —
 * the codebase the editor edits and the compiler mounts at /workspace.
 * The Site tab is the deployed static webpage folder — Build output; the
 * app pane renders its index.html through blob: URLs.
 * ------------------------------------------------------------------------ */

const wsTreeEl = document.getElementById('ws-tree');
const wsStatusEl = document.getElementById('ws-status');
const wsNewFileBtn = document.getElementById('ws-new-file');
const wsNewFolderBtn = document.getElementById('ws-new-folder');
const wsUploadBtn = document.getElementById('ws-upload-btn');
const wsUploadEl = document.getElementById('ws-upload');
const wsExportZipBtn = document.getElementById('ws-export-zip');
const siteTreeEl = document.getElementById('site-tree');
const siteStatusEl = document.getElementById('site-status');
const siteOpenTabBtn = document.getElementById('site-open-tab');
const siteRefreshBtn = document.getElementById('site-refresh');
const siteClearBtn = document.getElementById('site-clear');
const siteUploadBtn = document.getElementById('site-upload-btn');
const siteUploadEl = document.getElementById('site-upload');
const siteExportZipBtn = document.getElementById('site-export-zip');

const textDecoder = new TextDecoder();

/** Path of the workspace file currently open in the editor (null = none). */
let openPath = 'main.nim';

/** Collapsed folder paths per area (VS-Code-style tree state). */
const collapsed = { [AREA_WORKSPACE]: new Set(), [AREA_SITE]: new Set() };

/** One-line status inside a folder panel. */
function vfsStatus(el, msg, kind) {
  el.textContent = msg;
  el.className = `visible ${kind}`;
}

/** Status pill narration shared by the Run and Build flows. */
function narrateStep(msg) {
  if (msg.includes('step 1')) setStatus('Translating Nim to C…', 'busy');
  else if (msg.includes('step 2')) setStatus('Preparing the C code…', 'busy');
  else if (msg.includes('step 3')) setStatus('Compiling C to WebAssembly…', 'busy');
  else if (msg.includes('step 4')) setStatus('Running your app…', 'busy');
}

/* ----- the editor edits one workspace file at a time ----------------------*/

let saveTimer = null;

/** Debounced auto-save of the open file into the workspace store. */
function scheduleSave() {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(saveOpenFile, 400);
}

/** Flush the editor contents into the workspace store (no-op if none open). */
async function saveOpenFile() {
  if (saveTimer) { clearTimeout(saveTimer); saveTimer = null; }
  if (!openPath) return;
  try {
    await writeFile(AREA_WORKSPACE, openPath, editor.value);
  } catch (e) {
    log(`project: could not save ${openPath}: ${e.message || e}`, 'warn');
  }
}

/** Load a workspace file into the editor and switch to the Code tab. */
async function openFile(path) {
  await saveOpenFile(); // flush the file we are leaving
  const data = await readFile(AREA_WORKSPACE, path).catch(() => null);
  if (!data) {
    vfsStatus(wsStatusEl, `Could not open ${path}.`, 'err');
    return;
  }
  if (isLikelyBinary(data)) {
    vfsStatus(wsStatusEl, `"${path}" looks like a binary file — the editor only opens text.`, 'err');
    return;
  }
  openPath = path;
  editor.value = textDecoder.decode(data);
  tabCode.textContent = baseName(path);
  tabCode.title = path;
  updateLineNumbers();
  hideError();
  showTab('code');
  renderWorkspaceTree(); // refresh the .open highlight
}

/**
 * After a delete, make sure the editor is not pointing at a gone file:
 * fall back to main.nim / the first .nim file, or an empty editor.
 */
async function ensureOpenFileValid() {
  if (openPath) {
    const data = await readFile(AREA_WORKSPACE, openPath).catch(() => null);
    if (data) return;
  }
  let files = [];
  try { files = await listFiles(AREA_WORKSPACE); } catch (e) { /* empty */ }
  const real = files.filter((f) => !f.isDir);
  const pick = real.find((f) => f.path === 'main.nim')
    || real.find((f) => f.path.endsWith('.nim'))
    || real[0];
  openPath = null; // don't let openFile() re-save the deleted path
  if (pick) {
    await openFile(pick.path);
  } else {
    editor.value = '';
    tabCode.textContent = 'Code';
    tabCode.title = '';
    updateLineNumbers();
  }
}

/** First-run seed: an empty workspace gets the starter example as main.nim. */
async function seedWorkspace() {
  let files = [];
  try {
    files = await listFiles(AREA_WORKSPACE);
  } catch (e) {
    log(`project: file store unavailable (${e.message || e}) — edits will not persist`, 'warn');
  }
  let real = files.filter((f) => !f.isDir);
  if (real.length === 0) {
    try {
      await writeFile(AREA_WORKSPACE, 'main.nim', EXAMPLES[0].source);
      real = [{ path: 'main.nim', isDir: false }];
    } catch (e) { /* read-only store: session-only editing still works */ }
  }
  const pick = real.find((f) => f.path === 'main.nim')
    || real.find((f) => f.path.endsWith('.nim'))
    || real[0];
  if (pick) {
    openPath = pick.path;
    const data = await readFile(AREA_WORKSPACE, pick.path).catch(() => null);
    if (data && !isLikelyBinary(data)) editor.value = textDecoder.decode(data);
    tabCode.textContent = baseName(pick.path);
    tabCode.title = pick.path;
  }
  updateLineNumbers();
}

/* ----- tree rendering (shared by Project and Site) ------------------------*/

/** Build a nested node tree from flat vfs entries (folders may be implied). */
function buildTree(entries) {
  const root = { name: '', path: '', isDir: true, children: new Map() };
  const ensureDir = (path) => {
    let node = root;
    let acc = '';
    for (const seg of path.split('/')) {
      acc = acc ? `${acc}/${seg}` : seg;
      if (!node.children.has(acc)) {
        node.children.set(acc, { name: seg, path: acc, isDir: true, children: new Map(), implied: true });
      }
      node = node.children.get(acc);
    }
    return node;
  };
  for (const e of entries) {
    const segs = e.path.split('/');
    if (e.isDir) {
      const dir = ensureDir(e.path);
      dir.implied = false;
      dir.size = e.size;
      dir.updatedAt = e.updatedAt;
    } else {
      const parent = segs.length > 1 ? ensureDir(segs.slice(0, -1).join('/')) : root;
      parent.children.set(e.path, {
        name: segs[segs.length - 1], path: e.path, isDir: false,
        size: e.size, updatedAt: e.updatedAt, children: null,
      });
    }
  }
  return root;
}

/** Flatten the tree into visible rows (dirs first, honoring collapsed set). */
function flattenTree(root, area) {
  const rows = [];
  const walk = (node, depth) => {
    const kids = [...node.children.values()].sort((a, b) => (
      a.isDir === b.isDir ? a.name.localeCompare(b.name) : (a.isDir ? -1 : 1)
    ));
    for (const kid of kids) {
      rows.push({ node: kid, depth });
      if (kid.isDir && !collapsed[area].has(kid.path)) walk(kid, depth + 1);
    }
  };
  walk(root, 0);
  return rows;
}

/** The inline "type a name" row used by New file / New folder / Rename. */
function inlineInput(row, initial, onCommit) {
  const input = document.createElement('input');
  input.className = 'vfs-inline-input';
  input.value = initial;
  row.appendChild(input);
  input.focus();
  const slash = initial.lastIndexOf('/');
  input.setSelectionRange(slash + 1, initial.length);
  let done = false;
  const finish = (commit) => {
    if (done) return;
    done = true;
    const value = input.value.trim();
    input.remove();
    if (commit && value) onCommit(value);
  };
  input.addEventListener('keydown', (e) => {
    e.stopPropagation();
    if (e.key === 'Enter') finish(true);
    else if (e.key === 'Escape') finish(false);
  });
  input.addEventListener('blur', () => finish(true));
  input.addEventListener('click', (e) => e.stopPropagation());
}

/** Rename a row in place (works for files and folders, both areas). */
function startRename(row, node, area, refresh) {
  const statusEl = area === AREA_WORKSPACE ? wsStatusEl : siteStatusEl;
  const nameEl = row.querySelector('.vfs-name');
  if (nameEl) nameEl.style.display = 'none'; // the input takes its place
  inlineInput(row, node.path, async (target) => {
    if (target === node.path) { refresh(); return; }
    try {
      await saveOpenFile(); // don't let a pending save resurrect the old path
      const r = await renamePath(area, node.path, target);
      log(`${area === AREA_WORKSPACE ? 'project' : 'site'}: renamed ${r.from} -> ${r.to}`, 'info');
      if (area === AREA_WORKSPACE && openPath) {
        if (openPath === r.from) openPath = r.to;
        else if (openPath.startsWith(`${r.from}/`)) openPath = r.to + openPath.slice(r.from.length);
        tabCode.textContent = baseName(openPath);
        tabCode.title = openPath;
      }
    } catch (e) {
      vfsStatus(statusEl, `Rename failed: ${e.message || e}`, 'err');
    }
    refresh();
  });
}

/** Delete button; non-empty folders need a second click to confirm. */
function makeDeleteButton(node, area, refresh) {
  const statusEl = area === AREA_WORKSPACE ? wsStatusEl : siteStatusEl;
  const btn = document.createElement('button');
  btn.className = 'danger';
  btn.textContent = 'del';
  btn.title = node.isDir ? 'Delete this folder and everything in it' : 'Delete this file';
  btn.addEventListener('click', async (e) => {
    e.stopPropagation();
    const needsConfirm = node.isDir && node.children && node.children.size > 0;
    if (needsConfirm && btn.dataset.armed !== '1') {
      btn.dataset.armed = '1';
      btn.textContent = 'sure?';
      setTimeout(() => { btn.dataset.armed = ''; btn.textContent = 'del'; }, 3000);
      return;
    }
    try {
      if (saveTimer) { clearTimeout(saveTimer); saveTimer = null; }
      const n = await deletePath(area, node.path);
      log(`${area === AREA_WORKSPACE ? 'project' : 'site'}: deleted ${node.path} (${n} ${n === 1 ? 'entry' : 'entries'})`, 'info');
      if (area === AREA_WORKSPACE) await ensureOpenFileValid();
      else await renderSite();
    } catch (err) {
      vfsStatus(statusEl, `Delete failed: ${err.message || err}`, 'err');
    }
    refresh();
  });
  return btn;
}

/** One tree row. `extraActions` holds per-area buttons (e.g. download). */
function treeRow(node, depth, area, { onOpen, extraActions = [], badge = null }) {
  const row = document.createElement('div');
  row.className = 'vfs-row';
  if (node.isDir) row.classList.add('is-dir');
  if (!node.isDir && area === AREA_WORKSPACE && node.path === openPath) row.classList.add('open');
  row.style.paddingLeft = `${8 + depth * 14}px`;

  const icon = document.createElement('span');
  icon.className = 'vfs-icon';
  icon.textContent = node.isDir ? (collapsed[area].has(node.path) ? '▸' : '▾') : '';
  row.appendChild(icon);

  const name = document.createElement('span');
  name.className = 'vfs-name';
  name.textContent = node.name;
  name.title = node.path;
  row.appendChild(name);

  if (badge) {
    const b = document.createElement('span');
    b.className = 'vfs-entry-badge';
    b.textContent = badge;
    row.appendChild(b);
  }

  if (!node.isDir) {
    const meta = document.createElement('span');
    meta.className = 'vfs-meta';
    meta.textContent = fmtBytes(node.size || 0);
    row.appendChild(meta);
  }

  const actions = document.createElement('span');
  actions.className = 'row-actions';
  for (const extra of extraActions) actions.appendChild(extra);
  const ren = document.createElement('button');
  ren.textContent = 'ren';
  ren.title = 'Rename / move';
  ren.addEventListener('click', (e) => {
    e.stopPropagation();
    startRename(row, node, area, area === AREA_WORKSPACE ? renderWorkspaceTree : renderSiteTree);
  });
  actions.appendChild(ren);
  actions.appendChild(makeDeleteButton(node, area, area === AREA_WORKSPACE ? renderWorkspaceTree : renderSiteTree));
  row.appendChild(actions);

  row.addEventListener('click', () => {
    if (node.isDir) {
      if (collapsed[area].has(node.path)) collapsed[area].delete(node.path);
      else collapsed[area].add(node.path);
      (area === AREA_WORKSPACE ? renderWorkspaceTree : renderSiteTree)();
    } else if (onOpen) {
      onOpen(node);
    }
  });
  return row;
}

/** The "New file / New folder" inline input pinned at the top of a tree. */
function newEntryRow(area, isDir, refresh) {
  const row = document.createElement('div');
  row.className = 'vfs-row';
  const icon = document.createElement('span');
  icon.className = 'vfs-icon';
  row.appendChild(icon);
  inlineInput(row, '', async (value) => {
    try {
      if (isDir) {
        const p = await makeDir(area, value);
        log(`${area === AREA_WORKSPACE ? 'project' : 'site'}: new folder ${p}`, 'info');
      } else {
        const p = await writeFile(area, value, '');
        log(`${area === AREA_WORKSPACE ? 'project' : 'site'}: new file ${p}`, 'info');
        if (area === AREA_WORKSPACE && p.endsWith('.nim')) {
          refresh();
          await openFile(p);
          return;
        }
      }
    } catch (e) {
      vfsStatus(area === AREA_WORKSPACE ? wsStatusEl : siteStatusEl, e.message || String(e), 'err');
    }
    refresh();
  });
  return row;
}

/* ----- Project tab (Nim working folder) ------------------------------------*/

async function renderWorkspaceTree() {
  let entries = [];
  try {
    entries = await listFiles(AREA_WORKSPACE);
  } catch (e) {
    wsTreeEl.innerHTML = '';
    const div = document.createElement('div');
    div.className = 'vfs-empty';
    div.textContent = `The file store is unavailable: ${e.message || e}`;
    wsTreeEl.appendChild(div);
    return;
  }
  wsTreeEl.innerHTML = '';
  if (entries.length === 0) {
    const div = document.createElement('div');
    div.className = 'vfs-empty';
    div.textContent = 'Empty folder — use "New file" to get started.';
    wsTreeEl.appendChild(div);
    return;
  }
  for (const { node, depth } of flattenTree(buildTree(entries), AREA_WORKSPACE)) {
    wsTreeEl.appendChild(treeRow(node, depth, AREA_WORKSPACE, {
      onOpen: (n) => openFile(n.path),
      badge: node.path === 'main.nim' ? 'build entry' : null,
    }));
  }
}

wsNewFileBtn.addEventListener('click', () => {
  wsTreeEl.prepend(newEntryRow(AREA_WORKSPACE, false, renderWorkspaceTree));
});
wsNewFolderBtn.addEventListener('click', () => {
  wsTreeEl.prepend(newEntryRow(AREA_WORKSPACE, true, renderWorkspaceTree));
});
wsUploadBtn.addEventListener('click', () => wsUploadEl.click());
wsUploadEl.addEventListener('change', async () => {
  const files = [...(wsUploadEl.files || [])];
  wsUploadEl.value = '';
  for (const file of files) {
    try {
      const bytes = new Uint8Array(await file.arrayBuffer());
      await writeFile(AREA_WORKSPACE, file.name, bytes);
      log(`project: uploaded ${file.name} (${fmtBytes(bytes.length)})`, 'info');
    } catch (e) {
      vfsStatus(wsStatusEl, `Upload of ${file.name} failed: ${e.message || e}`, 'err');
    }
  }
  renderWorkspaceTree();
});

/* ----- Site tab (deployed static webpage folder) ---------------------------*/

/** Blob URLs backing the app-pane site preview; revoked on each re-render. */
let siteBlobUrls = [];

/**
 * Render the deployed site folder into the app pane: every file becomes a
 * blob: URL, quoted references in index.html are rewritten to them, and
 * the result runs in an iframe that fills the pane. Returns false when
 * there is no index.html yet.
 */
async function renderSite() {
  let files;
  try {
    files = await getFilesWithData(AREA_SITE);
  } catch (e) {
    return false;
  }
  const index = files.find((f) => f.path === 'index.html');
  if (!index) return false;
  for (const u of siteBlobUrls) URL.revokeObjectURL(u);
  siteBlobUrls = [];
  const urlMap = new Map();
  for (const f of files) {
    const url = URL.createObjectURL(new Blob([f.data], { type: mimeFor(f.path) }));
    siteBlobUrls.push(url);
    urlMap.set(f.path, url);
  }
  // The preview runs on the IDE host — that is development mode, which is
  // never domain-blocked: empty the embedded bound-domains list so the boot
  // gate stays disarmed here. Real static hosting keeps enforcement (the
  // index.html stored in the Site folder is untouched).
  const html = disarmDomainGateForPreview(rewriteSiteUrls(textDecoder.decode(index.data), urlMap));
  outputEl.innerHTML = '';
  outputEl.classList.add('site-mode');
  const iframe = document.createElement('iframe');
  iframe.setAttribute('title', 'deployed site preview');
  iframe.srcdoc = html;
  outputEl.appendChild(iframe);
  return true;
}

async function renderSiteTree() {
  let entries = [];
  try {
    entries = await listFiles(AREA_SITE);
  } catch (e) {
    siteTreeEl.innerHTML = '';
    const div = document.createElement('div');
    div.className = 'vfs-empty';
    div.textContent = `The file store is unavailable: ${e.message || e}`;
    siteTreeEl.appendChild(div);
    return;
  }
  siteTreeEl.innerHTML = '';
  if (entries.length === 0) {
    const div = document.createElement('div');
    div.className = 'vfs-empty';
    div.textContent = 'Nothing deployed yet — press Build to compile your project into this folder.';
    siteTreeEl.appendChild(div);
    return;
  }
  for (const { node, depth } of flattenTree(buildTree(entries), AREA_SITE)) {
    const dl = document.createElement('button');
    dl.textContent = 'save';
    dl.title = 'Download this file';
    dl.addEventListener('click', async (e) => {
      e.stopPropagation();
      const data = await readFile(AREA_SITE, node.path).catch(() => null);
      if (!data) return;
      const url = URL.createObjectURL(new Blob([data], { type: mimeFor(node.path) }));
      const a = document.createElement('a');
      a.href = url;
      a.download = baseName(node.path);
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 10000);
    });
    siteTreeEl.appendChild(treeRow(node, depth, AREA_SITE, {
      extraActions: node.isDir ? [] : [dl],
      badge: node.path === 'index.html' ? 'entry' : null,
    }));
  }
}

siteOpenTabBtn.addEventListener('click', async () => {
  const files = await getFilesWithData(AREA_SITE).catch(() => []);
  const index = files.find((f) => f.path === 'index.html');
  if (!index) {
    vfsStatus(siteStatusEl, 'No site yet — press Build first.', 'err');
    return;
  }
  const urlMap = new Map();
  for (const f of files) {
    urlMap.set(f.path, URL.createObjectURL(new Blob([f.data], { type: mimeFor(f.path) })));
  }
  const html = rewriteSiteUrls(textDecoder.decode(index.data), urlMap);
  const pageUrl = URL.createObjectURL(new Blob([html], { type: 'text/html' }));
  // Deliberately not revoked: the new tab reads these URLs for its lifetime.
  window.open(pageUrl, '_blank', 'noopener');
});

siteRefreshBtn.addEventListener('click', async () => {
  if (await renderSite()) {
    vfsStatus(siteStatusEl, 'The app pane is showing this folder’s index.html.', 'ok');
  } else {
    vfsStatus(siteStatusEl, 'No index.html in this folder yet — press Build first.', 'err');
  }
});

siteClearBtn.addEventListener('click', async () => {
  if (siteClearBtn.dataset.armed !== '1') {
    siteClearBtn.dataset.armed = '1';
    siteClearBtn.textContent = 'Really clear?';
    setTimeout(() => { siteClearBtn.dataset.armed = ''; siteClearBtn.textContent = 'Clear…'; }, 3000);
    return;
  }
  siteClearBtn.dataset.armed = '';
  siteClearBtn.textContent = 'Clear…';
  await clearArea(AREA_SITE);
  outputEl.classList.remove('site-mode');
  outputEl.innerHTML = '';
  log('site: folder cleared', 'info');
  renderSiteTree();
});

siteUploadBtn.addEventListener('click', () => siteUploadEl.click());
siteUploadEl.addEventListener('change', async () => {
  const files = [...(siteUploadEl.files || [])];
  siteUploadEl.value = '';
  for (const file of files) {
    try {
      const bytes = new Uint8Array(await file.arrayBuffer());
      await writeFile(AREA_SITE, file.name, bytes);
      log(`site: uploaded ${file.name} (${fmtBytes(bytes.length)})`, 'info');
    } catch (e) {
      vfsStatus(siteStatusEl, `Upload of ${file.name} failed: ${e.message || e}`, 'err');
    }
  }
  renderSiteTree();
});

/* ----- Export ZIP: download a whole folder as one archive ------------------*/

/**
 * Zip up every file (and explicit folder, so empty folders survive) in one
 * VFS area and offer it as a download. Shared by the Project and Site
 * toolbar buttons.
 *
 * @param {string} area AREA_WORKSPACE | AREA_SITE
 * @param {string} zipName download file name ("project.zip" / "site.zip")
 * @param {HTMLElement} statusEl panel status line for feedback
 */
async function exportAreaZip(area, zipName, statusEl) {
  try {
    if (area === AREA_WORKSPACE) await saveOpenFile(); // export what's on screen
    const [entries, files] = await Promise.all([listFiles(area), getFilesWithData(area)]);
    if (entries.length === 0) {
      vfsStatus(statusEl, 'Nothing to export yet — the folder is empty.', 'err');
      log(`${zipName}: nothing to export yet`, 'info');
      return;
    }
    const zipEntries = [
      ...entries.filter((e) => e.isDir).map((e) => ({ name: e.path, isDir: true })),
      ...files.map((f) => ({ name: f.path, data: f.data })),
    ].sort((a, b) => a.name.localeCompare(b.name));
    const bytes = zipFiles(zipEntries);
    const url = URL.createObjectURL(new Blob([bytes], { type: 'application/zip' }));
    const a = document.createElement('a');
    a.href = url;
    a.download = zipName;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    const folderCount = entries.filter((e) => e.isDir).length;
    const what = folderCount > 0 ? `${files.length} file(s), ${folderCount} folder(s)` : `${files.length} file(s)`;
    const msg = `exported ${what} as ${zipName} (${fmtBytes(bytes.length)})`;
    vfsStatus(statusEl, msg, 'ok');
    log(`${zipName}: ${msg}`, 'ok');
  } catch (e) {
    vfsStatus(statusEl, `Export failed: ${e.message || e}`, 'err');
    log(`${zipName}: export failed: ${e.message || e}`, 'error');
  }
}

wsExportZipBtn.addEventListener('click', () => exportAreaZip(AREA_WORKSPACE, 'project.zip', wsStatusEl));
siteExportZipBtn.addEventListener('click', () => exportAreaZip(AREA_SITE, 'site.zip', siteStatusEl));

/* ----- Build: compile the project into the Site folder ---------------------*/

/** Runtime modules fetched + stripped once per session, reused per Build. */
let siteRuntimeCache = null;

async function loadRuntimeForSite() {
  if (siteRuntimeCache) return siteRuntimeCache;
  const map = new Map();
  for (const f of RUNTIME_SITE_FILES) {
    const res = await fetch(f.src);
    if (!res.ok) throw new Error(`could not load ${f.src} (HTTP ${res.status})`);
    map.set(f.dest, stripEsmExports(await res.text()));
  }
  siteRuntimeCache = map;
  return map;
}

/* --------------------------------------------------------------------------
 * First-visit download with honest byte counting (SPEC §8c).
 * ------------------------------------------------------------------------ */

/** Format a byte count as a short MB string. */
function mb(bytes) {
  return (bytes / (1024 * 1024)).toFixed(0);
}

/**
 * Fetch one vendor file, counting bytes as they stream in.
 *
 * @param {{path: string, size: number, label: string}} file entry from VENDOR_FILES
 * @param {(done: number) => void} onBytes called with the cumulative count
 * @returns {Promise<Blob|null>} the file contents, or null if missing
 */
async function prefetchFile(file, onBytes) {
  const url = `${config.vendorUrl}/${file.path}`;
  let response;
  try {
    response = await fetch(url);
  } catch (e) {
    return null; // network hiccup: let the real loader surface the error
  }
  if (!response.ok || !response.body) return null; // optional file absent

  const reader = response.body.getReader();
  const chunks = [];
  let received = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    received += value.length;
    onBytes(value.length);
  }
  const type = file.path.endsWith('.wasm') ? 'application/wasm' : '';
  return new Blob(chunks, { type });
}

/**
 * Download every vendor file once, narrating progress in MB. Returns the
 * nim files as blobs so NimCompiler can load them from blob: URLs instead
 * of fetching them a second time.
 *
 * @returns {Promise<Map<string, Blob>>} basename -> blob for nim files
 */
async function prefetchVendor() {
  const total = VENDOR_FILES.reduce((acc, f) => acc + f.size, 0);
  let done = 0;
  progressWrap.classList.add('visible');
  const update = (label) => {
    const pct = Math.min(100, (done / total) * 100);
    progressBar.style.width = `${pct}%`;
    progressLabel.textContent =
      `Downloading the compiler (first visit only)… ${mb(done)} of about ${mb(total)} MB — ${label}`;
  };

  const preloaded = new Map();
  update('starting');
  for (const file of VENDOR_FILES) {
    update(file.label);
    const blob = await prefetchFile(file, (n) => {
      done += n;
      update(file.label);
    });
    if (blob && file.path.startsWith('nim/')) {
      preloaded.set(file.path.slice('nim/'.length), blob);
    }
  }
  progressBar.style.width = '100%';
  progressWrap.classList.remove('visible');
  return preloaded;
}

/* --------------------------------------------------------------------------
 * Toolchains + run flow.
 * ------------------------------------------------------------------------ */

let nim = null;
let clang = null;

/**
 * Resolves true the moment both toolchains finished loading (the same
 * moment Run/Build get enabled), false if initialization failed. Drives
 * window.NimIDE.ready().
 */
let resolveReady;
const readyPromise = new Promise((resolve) => { resolveReady = resolve; });

/**
 * Map a pipeline result to a one-line plain-English summary plus the raw
 * compiler output for the collapsible details (SPEC §8c).
 *
 * @param {{stage: string, error?: string, nimStdout: string,
 *   nimStderr: string, clangLog: string}} result
 * @returns {{summary: string, raw: string}}
 */
function friendlyError(result) {
  const raw = [
    result.error || '',
    result.nimStderr || '',
    result.nimStdout || '',
    result.clangLog || '',
  ].filter((s) => s && s.trim()).join('\n\n');

  if (result.stage === 'nim') {
    // Typical Nim error: "/workspace/main.nim(4, 10) Error: undeclared identifier: 'foo'"
    const m = /([\w./-]+\.nim)\((\d+),\s*\d+\)\s*Error:\s*(.+)/.exec(result.nimStderr || '');
    if (m) {
      return { summary: `The Nim compiler didn't understand ${m[1]} line ${m[2]}: ${m[3]}`, raw };
    }
    return { summary: "The Nim compiler couldn't understand your code. Details below.", raw };
  }
  if (result.stage === 'clang') {
    return { summary: 'The C build step reported a problem. Details below.', raw };
  }
  return { summary: `Your app was built, but it failed to start: ${result.error || 'unknown error'}`, raw };
}

/**
 * Load both toolchains in parallel after the one-time download; enable
 * the run button when ready.
 */
async function init() {
  setStatus('Loading compiler (first visit downloads about 75 MB)…', 'busy');
  try {
    const preloaded = await prefetchVendor();
    setStatus('Starting the compiler…', 'busy');
    nim = new NimCompiler({
      vendorUrl: config.vendorUrl,
      libpacksUrl: config.libpacksUrl,
      onLog: log,
      preloaded,
      // User-installed libraries from IndexedDB are re-read (and re-mounted
      // at /libs/<name>) on every compile.
      userLibs: getLibsWithFiles,
      // The Nim working folder (Project tab) is re-read and mounted at
      // /workspace on every compile, so multi-file projects just work.
      workspace: () => getFilesWithData(AREA_WORKSPACE),
    });
    clang = new ClangCompiler({ vendorUrl: config.vendorUrl, onLog: log });
    await Promise.all([nim.init(), clang.init()]);
    setStatus('Ready — press Run', 'ok');
    log('ready — press Run to build and run your program', 'ok');
    runBtn.disabled = false;
    buildBtn.disabled = false;
    resolveReady(true);
  } catch (e) {
    setStatus('The compiler failed to load', 'err');
    log(`initialization failed: ${e.message || e}`, 'error');
    resolveReady(false);
    showError(
      'The compiler could not be loaded. Check your internet connection and reload the page.',
      `initialization failed: ${e.message || e}\n\nexpected layout: ./vendor/nim/*, ./vendor/clang/*, ./libpacks/manifest.json next to index.html`
    );
  }
}

/**
 * Run: compile the file open in the editor (inside the mounted workspace,
 * so its sibling imports resolve) and run it right in the app pane.
 */
runBtn.addEventListener('click', async () => {
  if (!openPath || !openPath.endsWith('.nim')) {
    showError(
      'Open a .nim file to run it.',
      'The Run button compiles the file currently open in the editor. ' +
      'Open a .nim file from the Project tab, then press Run again.'
    );
    return;
  }
  runBtn.disabled = true;
  buildBtn.disabled = true;
  await saveOpenFile();
  outputEl.classList.remove('site-mode'); // leave the deployed-site view
  consoleEl.innerHTML = '';
  outputEl.innerHTML = '';
  hideError();
  const t0 = performance.now();
  try {
    const result = await compileAndRun({
      source: editor.value,
      outFile: `/workspace/${openPath}`,
      nim,
      clang,
      runtime: { createBindwebRunner },
      outputEl,
      onLog: (msg, kind) => {
        log(msg, kind);
        // Plain-English status narration for each pipeline stage (SPEC §8c).
        if (kind === 'step') narrateStep(msg);
      },
    });
    const dt = ((performance.now() - t0) / 1000).toFixed(1);
    if (result.ok) {
      setStatus(`Running — done in ${dt}s`, 'ok');
    } else {
      const { summary, raw } = friendlyError(result);
      setStatus('Something went wrong — see the message below', 'err');
      showError(summary, raw);
      log(summary, 'error');
    }
  } catch (e) {
    setStatus('Something went wrong — see the message below', 'err');
    showError('The build stopped unexpectedly. Details below.', e.stack || String(e));
    log(`pipeline error: ${e.message || e}`, 'error');
  } finally {
    runBtn.disabled = false;
    buildBtn.disabled = false;
  }
});

/** Swap the .nim extension for .wasm, keeping the folder structure. */
function wasmPathFor(nimPath) {
  return nimPath.replace(/\.nim$/, '.wasm');
}

/**
 * Build: compile EVERY .nim file in the Project tree into its own
 * self-contained .wasm in the deployed static webpage folder (Site tab)
 * — adios.nim -> adios.wasm, sub/mod.nim -> sub/mod.wasm. "Self-contained"
 * is literal: compileToWasm statically links the Nim runtime, wasi-libc
 * and the bindweb C runtime into each module, so every output wasm
 * includes the runtime. The generated index.html boots the entry wasm
 * (main.nim -> main.wasm, falling back to the .nim file open in the
 * editor); the other modules sit next to it for the site's own code to
 * load. A non-entry file that fails to compile is a warning, not a failed
 * Build.
 *
 * Hygiene: index.html is regenerated only while it still carries the
 * generated marker (hand edits survive) — a regenerated index.html gets
 * the whole JS runtime inlined (minified), so a stale nim-runtime/ folder
 * from older builds is deleted; a hand-edited index.html is kept and
 * nim-runtime/* is refreshed for it, so legacy pages referencing
 * nim-runtime/*.js keep working. Previously generated .wasm files whose
 * .nim source disappeared (incl. a legacy app.wasm) are deleted —
 * user-uploaded non-wasm assets are never touched.
 *
 * This is the EXACT flow the Build button runs; the button listener and
 * the window.NimIDE API both go through runBuild() below, so the
 * programmatic build is byte-for-byte the same pipeline with the same UI
 * side effects. Returns a plain, JSON-serializable result object
 * ({ok, summary, deployed, skipped, ...}) for the API; the button
 * ignores it.
 *
 * @returns {Promise<{ok: boolean, summary: string, deployed: string[],
 *   skipped: string[], indexRegenerated?: boolean, seconds?: string}>}
 */
async function performBuild() {
  const t0 = performance.now();
  try {
    await saveOpenFile();
    const projectFiles = await getFilesWithData(AREA_WORKSPACE);
    const nimFiles = projectFiles.filter((f) => f.path.endsWith('.nim'));
    const nimPaths = new Set(nimFiles.map((f) => f.path));

    // Entry selection: main.nim at the root, else the .nim file open in
    // the editor, else the current error dialog (unchanged behavior).
    let entry = 'main.nim';
    if (!nimPaths.has(entry)) {
      if (openPath && openPath.endsWith('.nim') && nimPaths.has(openPath)) {
        entry = openPath;
      } else {
        showError(
          'Nothing to build yet.',
          'Build compiles the project entry file "main.nim" (or the .nim file open in the editor). ' +
          'Create one in the Project tab, then press Build again.'
        );
        return { ok: false, summary: 'Nothing to build yet.', deployed: [], skipped: [] };
      }
    }

    // Compile the entry first (its failure fails the Build), then the rest
    // in path order. Sequential: one compiler instance, one MEMFS.
    const queue = [entry, ...nimFiles.map((f) => f.path).filter((p) => p !== entry).sort()];
    const dataByPath = new Map(nimFiles.map((f) => [f.path, f.data]));
    const deployed = []; // site-relative wasm paths, entry first
    const skipped = []; // non-entry files that failed to compile
    for (let i = 0; i < queue.length; i++) {
      const path = queue[i];
      log(`build: [${i + 1}/${queue.length}] compiling ${path}`, 'step');
      const result = await compileToWasm({ // eslint-disable-line no-await-in-loop
        source: path === openPath ? editor.value : textDecoder.decode(dataByPath.get(path)),
        outFile: `/workspace/${path}`,
        nim,
        clang,
        onLog: (msg, kind) => {
          log(msg, kind);
          if (kind === 'step') narrateStep(msg);
        },
      });
      if (!result.ok) {
        if (path === entry) {
          const { summary, raw } = friendlyError(result);
          setStatus('Build failed — see the message below', 'err');
          showError(summary, raw);
          log(summary, 'error');
          return { ok: false, summary, deployed: [], skipped };
        }
        const { summary } = friendlyError(result);
        // Don't ship a stale wasm for a file that no longer compiles.
        const staleWasm = wasmPathFor(path);
        const removed = await deletePath(AREA_SITE, staleWasm); // eslint-disable-line no-await-in-loop
        log(`build: warning: ${path} failed to compile and was skipped — ${summary}`, 'warn');
        if (removed) log(`build: removed stale ${staleWasm} left over from a previous build`, 'info');
        skipped.push(removed ? `${path} (stale wasm removed)` : path);
        continue;
      }
      const wasmPath = wasmPathFor(path);
      await writeFile(AREA_SITE, wasmPath, result.wasm); // eslint-disable-line no-await-in-loop
      deployed.push(wasmPath);
    }

    setStatus('Deploying to the Site folder…', 'busy');
    const runtime = await loadRuntimeForSite();

    // Domain binding (bindDomain("...")): scan ALL project .nim sources for
    // bound hostnames. The generated index.html embeds them (normalized,
    // unique) plus the wasm manifest (entry first, rest sorted — exactly
    // the `deployed` order) so the boot script can abort on a foreign
    // domain BEFORE any fetch and load the manifest strictly one-by-one.
    const boundDomains = collectBoundDomains(
      nimFiles.map((f) => (f.path === openPath ? editor.value : textDecoder.decode(f.data)))
    );
    const wasmManifest = deployed.slice();
    if (boundDomains.length) {
      log(`build: domain binding active for ${boundDomains.join(', ')} — the deployed site will only boot there`, 'info');
    }

    const existingIndex = await readFile(AREA_SITE, 'index.html').catch(() => null);
    const existingText = existingIndex ? textDecoder.decode(existingIndex) : null;
    let indexRegenerated = false;
    if (!existingText || existingText.includes(SITE_GENERATED_MARKER)) {
      // Generated site = wasm files + index.html with the runtime inlined
      // (minified); no nim-runtime/ folder. Remove a stale one left by
      // older builds (or by a previously hand-edited index.html).
      const removedRuntime = await deletePath(AREA_SITE, 'nim-runtime');
      if (removedRuntime) {
        log('build: removed the old nim-runtime/ folder — the runtime is now inlined into index.html', 'info');
      }
      const runtimeScripts = [
        ...RUNTIME_SITE_FILES.map((f) => ({
          name: f.dest.slice('nim-runtime/'.length),
          code: runtime.get(f.dest),
        })),
        { name: 'boot.js', code: SITE_BOOT_JS },
      ];
      await writeFile(AREA_SITE, 'index.html',
        generateSiteIndex(entry, wasmPathFor(entry), runtimeScripts, { boundDomains, wasmManifest }));
      indexRegenerated = true;
      log(`build: index.html generated (boots ${wasmPathFor(entry)}; runtime inlined as an obfuscated payload)`, 'info');
    } else {
      // Legacy mode: a hand-edited index.html may still reference
      // nim-runtime/*.js, so keep those files fresh alongside it.
      for (const [dest, text] of runtime) {
        await writeFile(AREA_SITE, dest, text); // eslint-disable-line no-await-in-loop
      }
      await writeFile(AREA_SITE, 'nim-runtime/boot.js', SITE_BOOT_JS);
      log('build: keeping your hand-edited index.html (not regenerated) — refreshed nim-runtime/* so its <script src="nim-runtime/..."> references keep working', 'info');
    }

    // Stale-output hygiene: delete site .wasm files whose matching .nim
    // source is gone (covers a legacy app.wasm too). Only .wasm files are
    // candidates, so user uploads are never deleted.
    const siteEntries = await listFiles(AREA_SITE).catch(() => []);
    for (const rec of siteEntries) {
      if (rec.isDir || !rec.path.endsWith('.wasm')) continue;
      const nimSource = rec.path.replace(/\.wasm$/, '.nim');
      if (!nimPaths.has(nimSource)) {
        await deletePath(AREA_SITE, rec.path); // eslint-disable-line no-await-in-loop
        log(`build: removed stale ${rec.path} (no matching .nim in the project)`, 'info');
      }
    }

    await renderSite();
    renderSiteTree();
    const dt = ((performance.now() - t0) / 1000).toFixed(1);
    setStatus(`Site deployed — built in ${dt}s`, 'ok');
    let line = `build: deployed ${deployed.length} wasm module(s) (${deployed.join(', ')}) + index.html`;
    line += indexRegenerated ? ' (runtime inlined)' : ' + nim-runtime/';
    if (skipped.length) line += ` — skipped ${skipped.length} file(s) that failed to compile (${skipped.join(', ')})`;
    log(line, skipped.length ? 'warn' : 'ok');
    return { ok: true, summary: line, deployed, skipped, indexRegenerated, seconds: dt };
  } catch (e) {
    setStatus('Build failed — see the message below', 'err');
    showError('The build stopped unexpectedly. Details below.', e.stack || String(e));
    log(`build error: ${e.message || e}`, 'error');
    return { ok: false, summary: `build error: ${e.message || e}`, deployed: [], skipped: [] };
  }
}

/**
 * One-build-at-a-time guard shared by the Build button and the
 * window.NimIDE API: while a build is in flight (from either path) the
 * Build/Run buttons stay disabled and a second build request is refused.
 * Clears the console pane and hides the error box, exactly like the
 * button always did.
 *
 * @returns {Promise<object>} performBuild()'s plain result object
 */
let buildInFlight = false;
async function runBuild() {
  if (buildInFlight) {
    const summary = 'a build is already running — wait for it to finish';
    log(`build: ${summary}`, 'warn');
    return { ok: false, summary, deployed: [], skipped: [] };
  }
  buildInFlight = true;
  buildBtn.disabled = true;
  runBtn.disabled = true;
  consoleEl.innerHTML = '';
  hideError();
  try {
    return await performBuild();
  } finally {
    buildBtn.disabled = false;
    runBtn.disabled = false;
    buildInFlight = false;
  }
}

buildBtn.addEventListener('click', () => { runBuild(); });

/* --------------------------------------------------------------------------
 * window.NimIDE — GUI-less driving API (ai-api.js), for AI/CLI agents
 * driving this page via the DevTools console / CDP Runtime.evaluate /
 * Playwright. Everything below is hooks into the pieces above; the API
 * itself lives in ai-api.js and is documented in AI.md / SKILL.md.
 * ------------------------------------------------------------------------ */

installNimIDE({
  version: '1.0.0',
  ready: () => readyPromise,
  status: () => statusEl.textContent,
  runBuild,
  addLogListener,
  saveOpenFile,
  // An API write over the file open in the editor must land in the editor
  // too — otherwise the next auto-save / build would clobber it with the
  // stale editor contents.
  syncEditor: (path, text) => {
    if (openPath === path && typeof text === 'string') {
      editor.value = text;
      updateLineNumbers();
    }
  },
  refreshTrees: () => { renderWorkspaceTree(); renderSiteTree(); },
});

/* --------------------------------------------------------------------------
 * Startup: load the working folder into the editor, restore a previously
 * deployed site into the app pane, then start the toolchains.
 * ------------------------------------------------------------------------ */

(async () => {
  await seedWorkspace();
  try {
    if (await renderSite()) {
      log('site: showing your deployed site from the last session', 'info');
    }
  } catch (e) { /* no site yet */ }
  init();
})();
