
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## AUDIO namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc play*(handle: AudioHandle) =
  ## audio.PLAY (opcode 0x6B)
  pushCommand(0x6Bu32)
  pushData(handle.int32)

proc pause*(handle: AudioHandle) =
  ## audio.PAUSE (opcode 0x6C)
  pushCommand(0x6Cu32)
  pushData(handle.int32)

proc set_volume*(handle: AudioHandle, vol: float64) =
  ## audio.SET_VOLUME (opcode 0x6D)
  pushCommand(0x6Du32)
  pushData(handle.int32)
  pushData(vol.float64)

proc set_loop*(handle: AudioHandle, loop: uint8) =
  ## audio.SET_LOOP (opcode 0x6E)
  pushCommand(0x6Eu32)
  pushData(handle.int32)
  pushData(loop.uint32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_audio_create_audio(src: cstring; srcLen: uint32): int32 {.importc.}
proc bindweb_audio_get_current_time(handle: int32): float64 {.importc.}
proc bindweb_audio_get_duration(handle: int32): float64 {.importc.}

proc create_audio*(src: string): AudioHandle =
  ## audio.CREATE_AUDIO
  flush()
  return AudioHandle(bindweb_audio_create_audio(src.cstring, src.len.uint32))

proc get_current_time*(handle: AudioHandle): float64 =
  ## audio.GET_CURRENT_TIME
  flush()
  return bindweb_audio_get_current_time(int32(handle))

proc get_duration*(handle: AudioHandle): float64 =
  ## audio.GET_DURATION
  flush()
  return bindweb_audio_get_duration(int32(handle))

