
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## CANVAS namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc set_size*(handle: CanvasHandle, width: float64, height: float64) =
  ## canvas.SET_SIZE (opcode 0x22)
  pushCommand(0x22u32)
  pushData(handle.int32)
  pushData(width.float64)
  pushData(height.float64)

proc set_fill_style*(handle: CanvasContext2DHandle, r: uint8, g: uint8, b: uint8) =
  ## canvas.SET_FILL_STYLE (opcode 0x23)
  pushCommand(0x23u32)
  pushData(handle.int32)
  pushData(r.uint32)
  pushData(g.uint32)
  pushData(b.uint32)

proc set_fill_style_str*(handle: CanvasContext2DHandle, color: string) =
  ## canvas.SET_FILL_STYLE_STR (opcode 0x24)
  pushCommand(0x24u32)
  pushData(handle.int32)
  pushString(color)

proc fill_rect*(handle: CanvasContext2DHandle, x: float64, y: float64, w: float64, h: float64) =
  ## canvas.FILL_RECT (opcode 0x25)
  pushCommand(0x25u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(w.float64)
  pushData(h.float64)

proc clear_rect*(handle: CanvasContext2DHandle, x: float64, y: float64, w: float64, h: float64) =
  ## canvas.CLEAR_RECT (opcode 0x26)
  pushCommand(0x26u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(w.float64)
  pushData(h.float64)

proc stroke_rect*(handle: CanvasContext2DHandle, x: float64, y: float64, w: float64, h: float64) =
  ## canvas.STROKE_RECT (opcode 0x27)
  pushCommand(0x27u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(w.float64)
  pushData(h.float64)

proc set_stroke_style*(handle: CanvasContext2DHandle, r: uint8, g: uint8, b: uint8) =
  ## canvas.SET_STROKE_STYLE (opcode 0x28)
  pushCommand(0x28u32)
  pushData(handle.int32)
  pushData(r.uint32)
  pushData(g.uint32)
  pushData(b.uint32)

proc set_stroke_style_str*(handle: CanvasContext2DHandle, color: string) =
  ## canvas.SET_STROKE_STYLE_STR (opcode 0x29)
  pushCommand(0x29u32)
  pushData(handle.int32)
  pushString(color)

proc set_line_width*(handle: CanvasContext2DHandle, width: float64) =
  ## canvas.SET_LINE_WIDTH (opcode 0x2A)
  pushCommand(0x2Au32)
  pushData(handle.int32)
  pushData(width.float64)

proc begin_path*(handle: CanvasContext2DHandle) =
  ## canvas.BEGIN_PATH (opcode 0x2B)
  pushCommand(0x2Bu32)
  pushData(handle.int32)

proc close_path*(handle: CanvasContext2DHandle) =
  ## canvas.CLOSE_PATH (opcode 0x2C)
  pushCommand(0x2Cu32)
  pushData(handle.int32)

proc move_to*(handle: CanvasContext2DHandle, x: float64, y: float64) =
  ## canvas.MOVE_TO (opcode 0x2D)
  pushCommand(0x2Du32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)

proc line_to*(handle: CanvasContext2DHandle, x: float64, y: float64) =
  ## canvas.LINE_TO (opcode 0x2E)
  pushCommand(0x2Eu32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)

proc stroke*(handle: CanvasContext2DHandle) =
  ## canvas.STROKE (opcode 0x2F)
  pushCommand(0x2Fu32)
  pushData(handle.int32)

proc fill*(handle: CanvasContext2DHandle) =
  ## canvas.FILL (opcode 0x30)
  pushCommand(0x30u32)
  pushData(handle.int32)

proc arc*(handle: CanvasContext2DHandle, x: float64, y: float64, radius: float64, start_angle: float64, end_angle: float64) =
  ## canvas.ARC (opcode 0x31)
  pushCommand(0x31u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(radius.float64)
  pushData(start_angle.float64)
  pushData(end_angle.float64)

proc fill_text*(handle: CanvasContext2DHandle, text: string, x: float64, y: float64) =
  ## canvas.FILL_TEXT (opcode 0x32)
  pushCommand(0x32u32)
  pushData(handle.int32)
  pushString(text)
  pushData(x.float64)
  pushData(y.float64)

proc fill_text_f*(handle: CanvasContext2DHandle, fmt: string, val: float64, x: float64, y: float64) =
  ## canvas.FILL_TEXT_F (opcode 0x33)
  pushCommand(0x33u32)
  pushData(handle.int32)
  pushString(fmt)
  pushData(val.float64)
  pushData(x.float64)
  pushData(y.float64)

proc fill_text_i*(handle: CanvasContext2DHandle, fmt: string, val: int32, x: float64, y: float64) =
  ## canvas.FILL_TEXT_I (opcode 0x34)
  pushCommand(0x34u32)
  pushData(handle.int32)
  pushString(fmt)
  pushData(val.int32)
  pushData(x.float64)
  pushData(y.float64)

proc set_font*(handle: CanvasContext2DHandle, font: string) =
  ## canvas.SET_FONT (opcode 0x35)
  pushCommand(0x35u32)
  pushData(handle.int32)
  pushString(font)

proc set_text_align*(handle: CanvasContext2DHandle, align: string) =
  ## canvas.SET_TEXT_ALIGN (opcode 0x36)
  pushCommand(0x36u32)
  pushData(handle.int32)
  pushString(align)

proc draw_image*(handle: CanvasContext2DHandle, img_handle: ImageHandle, x: float64, y: float64) =
  ## canvas.DRAW_IMAGE (opcode 0x37)
  pushCommand(0x37u32)
  pushData(handle.int32)
  pushData(img_handle.int32)
  pushData(x.float64)
  pushData(y.float64)

proc translate*(handle: CanvasContext2DHandle, x: float64, y: float64) =
  ## canvas.TRANSLATE (opcode 0x38)
  pushCommand(0x38u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)

proc rotate*(handle: CanvasContext2DHandle, angle: float64) =
  ## canvas.ROTATE (opcode 0x39)
  pushCommand(0x39u32)
  pushData(handle.int32)
  pushData(angle.float64)

proc scale*(handle: CanvasContext2DHandle, x: float64, y: float64) =
  ## canvas.SCALE (opcode 0x3A)
  pushCommand(0x3Au32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)

proc save*(handle: CanvasContext2DHandle) =
  ## canvas.SAVE (opcode 0x3B)
  pushCommand(0x3Bu32)
  pushData(handle.int32)

proc restore*(handle: CanvasContext2DHandle) =
  ## canvas.RESTORE (opcode 0x3C)
  pushCommand(0x3Cu32)
  pushData(handle.int32)

proc log_canvas_info*(handle: CanvasHandle) =
  ## canvas.LOG_CANVAS_INFO (opcode 0x3D)
  pushCommand(0x3Du32)
  pushData(handle.int32)

proc set_global_alpha*(handle: CanvasContext2DHandle, alpha: float64) =
  ## canvas.SET_GLOBAL_ALPHA (opcode 0x3E)
  pushCommand(0x3Eu32)
  pushData(handle.int32)
  pushData(alpha.float64)

proc set_line_cap*(handle: CanvasContext2DHandle, cap: string) =
  ## canvas.SET_LINE_CAP (opcode 0x3F)
  pushCommand(0x3Fu32)
  pushData(handle.int32)
  pushString(cap)

proc set_line_join*(handle: CanvasContext2DHandle, join: string) =
  ## canvas.SET_LINE_JOIN (opcode 0x40)
  pushCommand(0x40u32)
  pushData(handle.int32)
  pushString(join)

proc set_shadow*(handle: CanvasContext2DHandle, blur: float64, off_x: float64, off_y: float64, color: string) =
  ## canvas.SET_SHADOW (opcode 0x41)
  pushCommand(0x41u32)
  pushData(handle.int32)
  pushData(blur.float64)
  pushData(off_x.float64)
  pushData(off_y.float64)
  pushString(color)

proc bezier_curve_to*(handle: CanvasContext2DHandle, cp1x: float64, cp1y: float64, cp2x: float64, cp2y: float64, x: float64, y: float64) =
  ## canvas.BEZIER_CURVE_TO (opcode 0x42)
  pushCommand(0x42u32)
  pushData(handle.int32)
  pushData(cp1x.float64)
  pushData(cp1y.float64)
  pushData(cp2x.float64)
  pushData(cp2y.float64)
  pushData(x.float64)
  pushData(y.float64)

proc quadratic_curve_to*(handle: CanvasContext2DHandle, cpx: float64, cpy: float64, x: float64, y: float64) =
  ## canvas.QUADRATIC_CURVE_TO (opcode 0x43)
  pushCommand(0x43u32)
  pushData(handle.int32)
  pushData(cpx.float64)
  pushData(cpy.float64)
  pushData(x.float64)
  pushData(y.float64)

proc rect*(handle: CanvasContext2DHandle, x: float64, y: float64, w: float64, h: float64) =
  ## canvas.RECT (opcode 0x44)
  pushCommand(0x44u32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(w.float64)
  pushData(h.float64)

proc clip*(handle: CanvasContext2DHandle) =
  ## canvas.CLIP (opcode 0x45)
  pushCommand(0x45u32)
  pushData(handle.int32)

proc stroke_text*(handle: CanvasContext2DHandle, text: string, x: float64, y: float64) =
  ## canvas.STROKE_TEXT (opcode 0x46)
  pushCommand(0x46u32)
  pushData(handle.int32)
  pushString(text)
  pushData(x.float64)
  pushData(y.float64)

proc set_text_baseline*(handle: CanvasContext2DHandle, baseline: string) =
  ## canvas.SET_TEXT_BASELINE (opcode 0x47)
  pushCommand(0x47u32)
  pushData(handle.int32)
  pushString(baseline)

proc set_global_composite_operation*(handle: CanvasContext2DHandle, op: string) =
  ## canvas.SET_GLOBAL_COMPOSITE_OPERATION (opcode 0x48)
  pushCommand(0x48u32)
  pushData(handle.int32)
  pushString(op)

proc draw_image_scaled*(handle: CanvasContext2DHandle, img_handle: ImageHandle, x: float64, y: float64, w: float64, h: float64) =
  ## canvas.DRAW_IMAGE_SCALED (opcode 0x49)
  pushCommand(0x49u32)
  pushData(handle.int32)
  pushData(img_handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(w.float64)
  pushData(h.float64)

proc draw_image_full*(handle: CanvasContext2DHandle, img_handle: ImageHandle, sx: float64, sy: float64, sw: float64, sh: float64, dx: float64, dy: float64, dw: float64, dh: float64) =
  ## canvas.DRAW_IMAGE_FULL (opcode 0x4A)
  pushCommand(0x4Au32)
  pushData(handle.int32)
  pushData(img_handle.int32)
  pushData(sx.float64)
  pushData(sy.float64)
  pushData(sw.float64)
  pushData(sh.float64)
  pushData(dx.float64)
  pushData(dy.float64)
  pushData(dw.float64)
  pushData(dh.float64)

proc reset_transform*(handle: CanvasContext2DHandle) =
  ## canvas.RESET_TRANSFORM (opcode 0x4B)
  pushCommand(0x4Bu32)
  pushData(handle.int32)

proc ellipse*(handle: CanvasContext2DHandle, x: float64, y: float64, radius_x: float64, radius_y: float64, rotation: float64, start_angle: float64, end_angle: float64, counter_clockwise: uint8) =
  ## canvas.ELLIPSE (opcode 0x4C)
  pushCommand(0x4Cu32)
  pushData(handle.int32)
  pushData(x.float64)
  pushData(y.float64)
  pushData(radius_x.float64)
  pushData(radius_y.float64)
  pushData(rotation.float64)
  pushData(start_angle.float64)
  pushData(end_angle.float64)
  pushData(counter_clockwise.uint32)

proc arc_to*(handle: CanvasContext2DHandle, x1: float64, y1: float64, x2: float64, y2: float64, radius: float64) =
  ## canvas.ARC_TO (opcode 0x4D)
  pushCommand(0x4Du32)
  pushData(handle.int32)
  pushData(x1.float64)
  pushData(y1.float64)
  pushData(x2.float64)
  pushData(y2.float64)
  pushData(radius.float64)

proc set_transform*(handle: CanvasContext2DHandle, a: float64, b: float64, c: float64, d: float64, e: float64, f: float64) =
  ## canvas.SET_TRANSFORM (opcode 0x4E)
  pushCommand(0x4Eu32)
  pushData(handle.int32)
  pushData(a.float64)
  pushData(b.float64)
  pushData(c.float64)
  pushData(d.float64)
  pushData(e.float64)
  pushData(f.float64)

proc transform*(handle: CanvasContext2DHandle, a: float64, b: float64, c: float64, d: float64, e: float64, f: float64) =
  ## canvas.TRANSFORM (opcode 0x4F)
  pushCommand(0x4Fu32)
  pushData(handle.int32)
  pushData(a.float64)
  pushData(b.float64)
  pushData(c.float64)
  pushData(d.float64)
  pushData(e.float64)
  pushData(f.float64)

proc set_miter_limit*(handle: CanvasContext2DHandle, limit: float64) =
  ## canvas.SET_MITER_LIMIT (opcode 0x50)
  pushCommand(0x50u32)
  pushData(handle.int32)
  pushData(limit.float64)

proc set_image_smoothing_enabled*(handle: CanvasContext2DHandle, enabled: uint8) =
  ## canvas.SET_IMAGE_SMOOTHING_ENABLED (opcode 0x51)
  pushCommand(0x51u32)
  pushData(handle.int32)
  pushData(enabled.uint32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_canvas_create_canvas(dom_id: cstring; dom_idLen: uint32; width: float64; height: float64): int32 {.importc.}
proc bindweb_canvas_get_context_2d(canvas_handle: int32): int32 {.importc.}
proc bindweb_canvas_get_context_webgl(canvas_handle: int32): int32 {.importc.}
proc bindweb_canvas_get_context_webgpu(canvas_handle: int32): int32 {.importc.}
proc bindweb_canvas_measure_text_width(handle: int32; text: cstring; textLen: uint32): float64 {.importc.}

proc create_canvas*(dom_id: string; width: float64; height: float64): CanvasHandle =
  ## canvas.CREATE_CANVAS
  flush()
  return CanvasHandle(bindweb_canvas_create_canvas(dom_id.cstring, dom_id.len.uint32, width, height))

proc get_context_2d*(canvas_handle: CanvasHandle): CanvasContext2DHandle =
  ## canvas.GET_CONTEXT_2D
  flush()
  return CanvasContext2DHandle(bindweb_canvas_get_context_2d(int32(canvas_handle)))

proc get_context_webgl*(canvas_handle: CanvasHandle): WebGLContextHandle =
  ## canvas.GET_CONTEXT_WEBGL
  flush()
  return WebGLContextHandle(bindweb_canvas_get_context_webgl(int32(canvas_handle)))

proc get_context_webgpu*(canvas_handle: CanvasHandle): WGPUContextHandle =
  ## canvas.GET_CONTEXT_WEBGPU
  flush()
  return WGPUContextHandle(bindweb_canvas_get_context_webgpu(int32(canvas_handle)))

proc measure_text_width*(handle: CanvasContext2DHandle; text: string): float64 =
  ## canvas.MEASURE_TEXT_WIDTH
  flush()
  return bindweb_canvas_measure_text_width(int32(handle), text.cstring, text.len.uint32)

