
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## DOM namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  CLICK_EVENT_OPCODE* = 0x01'u8
  INPUT_EVENT_OPCODE* = 0x02'u8
  CHANGE_EVENT_OPCODE* = 0x03'u8
  KEYDOWN_EVENT_OPCODE* = 0x04'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  ClickEvent* = object
    ## Event: CLICK (opcode 0x01)
    handle*: DOMElementHandle

  InputEvent* = object
    ## Event: INPUT (opcode 0x02)
    handle*: DOMElementHandle
    value*: string

  ChangeEvent* = object
    ## Event: CHANGE (opcode 0x03)
    handle*: DOMElementHandle
    value*: string

  KeydownEvent* = object
    ## Event: KEYDOWN (opcode 0x04)
    handle*: DOMElementHandle
    keycode*: int32

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parseClickEvent*(data: ptr uint8; len: uint32): ClickEvent =
  ## Parse CLICK event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[DOMElementHandle](readInt32(data, offset))

proc parseInputEvent*(data: ptr uint8; len: uint32): InputEvent =
  ## Parse INPUT event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[DOMElementHandle](readInt32(data, offset))
  result.value = readString(data, offset)

proc parseChangeEvent*(data: ptr uint8; len: uint32): ChangeEvent =
  ## Parse CHANGE event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[DOMElementHandle](readInt32(data, offset))
  result.value = readString(data, offset)

proc parseKeydownEvent*(data: ptr uint8; len: uint32): KeydownEvent =
  ## Parse KEYDOWN event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[DOMElementHandle](readInt32(data, offset))
  result.keycode = cast[int32](readInt32(data, offset))


# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc create_element_deferred*(handle: int32, tag: string) =
  ## dom.CREATE_ELEMENT_DEFERRED (opcode 0x05)
  pushCommand(0x05u32)
  pushData(handle.int32)
  pushString(tag)

proc create_element_deferred_scoped*(handle: int32, tag: string, scope: string) =
  ## dom.CREATE_ELEMENT_DEFERRED_SCOPED (opcode 0x06)
  pushCommand(0x06u32)
  pushData(handle.int32)
  pushString(tag)
  pushString(scope)

proc create_comment_deferred*(handle: int32, text: string) =
  ## dom.CREATE_COMMENT_DEFERRED (opcode 0x08)
  pushCommand(0x08u32)
  pushData(handle.int32)
  pushString(text)

proc create_text_node_deferred*(handle: int32, text: string) =
  ## dom.CREATE_TEXT_NODE_DEFERRED (opcode 0x0A)
  pushCommand(0x0Au32)
  pushData(handle.int32)
  pushString(text)

proc set_node_value*(handle: DOMElementHandle, text: string) =
  ## dom.SET_NODE_VALUE (opcode 0x0B)
  pushCommand(0x0Bu32)
  pushData(handle.int32)
  pushString(text)

proc set_attribute*(handle: DOMElementHandle, name: string, value: string) =
  ## dom.SET_ATTRIBUTE (opcode 0x0C)
  pushCommand(0x0Cu32)
  pushData(handle.int32)
  pushString(name)
  pushString(value)

proc set_property*(handle: DOMElementHandle, name: string, value: string) =
  ## dom.SET_PROPERTY (opcode 0x0D)
  pushCommand(0x0Du32)
  pushData(handle.int32)
  pushString(name)
  pushString(value)

proc append_child*(parent_handle: DOMElementHandle, child_handle: DOMElementHandle) =
  ## dom.APPEND_CHILD (opcode 0x0F)
  pushCommand(0x0Fu32)
  pushData(parent_handle.int32)
  pushData(child_handle.int32)

proc insert_before*(parent_handle: DOMElementHandle, child_handle: DOMElementHandle, ref_handle: DOMElementHandle) =
  ## dom.INSERT_BEFORE (opcode 0x10)
  pushCommand(0x10u32)
  pushData(parent_handle.int32)
  pushData(child_handle.int32)
  pushData(ref_handle.int32)

proc remove_element*(handle: DOMElementHandle) =
  ## dom.REMOVE_ELEMENT (opcode 0x11)
  pushCommand(0x11u32)
  pushData(handle.int32)

proc release_handle*(handle: DOMElementHandle) =
  ## dom.RELEASE_HANDLE (opcode 0x1E)
  ## Release a handle slot for GC recycling. Does NOT remove the DOM element.
  pushCommand(0x1Eu32)
  pushData(handle.int32)

proc inject_script*(code: string) =
  ## dom.INJECT_SCRIPT (opcode 0x1F)
  ## Inject a real <script> element into document.head. Unlike innerHTML, this executes.
  pushCommand(0x1Fu32)
  pushString(code)

proc move_before*(parent_handle: DOMElementHandle, node_handle: DOMElementHandle, ref_handle: DOMElementHandle) =
  ## dom.MOVE_BEFORE (opcode 0x12)
  pushCommand(0x12u32)
  pushData(parent_handle.int32)
  pushData(node_handle.int32)
  pushData(ref_handle.int32)

proc set_inner_html*(handle: DOMElementHandle, html: string) =
  ## dom.SET_INNER_HTML (opcode 0x13)
  pushCommand(0x13u32)
  pushData(handle.int32)
  pushString(html)

proc set_inner_text*(handle: DOMElementHandle, text: string) =
  ## dom.SET_INNER_TEXT (opcode 0x14)
  pushCommand(0x14u32)
  pushData(handle.int32)
  pushString(text)

proc add_class*(handle: DOMElementHandle, cls: string) =
  ## dom.ADD_CLASS (opcode 0x15)
  pushCommand(0x15u32)
  pushData(handle.int32)
  pushString(cls)

proc remove_class*(handle: DOMElementHandle, cls: string) =
  ## dom.REMOVE_CLASS (opcode 0x16)
  pushCommand(0x16u32)
  pushData(handle.int32)
  pushString(cls)

proc add_click_listener*(handle: DOMElementHandle) =
  ## dom.ADD_CLICK_LISTENER (opcode 0x17)
  pushCommand(0x17u32)
  pushData(handle.int32)

proc add_input_listener*(handle: DOMElementHandle) =
  ## dom.ADD_INPUT_LISTENER (opcode 0x18)
  pushCommand(0x18u32)
  pushData(handle.int32)

proc add_change_listener*(handle: DOMElementHandle) =
  ## dom.ADD_CHANGE_LISTENER (opcode 0x19)
  pushCommand(0x19u32)
  pushData(handle.int32)

proc add_keydown_listener*(handle: DOMElementHandle) =
  ## dom.ADD_KEYDOWN_LISTENER (opcode 0x1A)
  pushCommand(0x1Au32)
  pushData(handle.int32)

proc request_fullscreen*(handle: DOMElementHandle) =
  ## dom.REQUEST_FULLSCREEN (opcode 0x1B)
  pushCommand(0x1Bu32)
  pushData(handle.int32)

proc request_pointer_lock*(handle: DOMElementHandle) =
  ## dom.REQUEST_POINTER_LOCK (opcode 0x1C)
  pushCommand(0x1Cu32)
  pushData(handle.int32)

proc scroll_to_top*() =
  ## dom.SCROLL_TO_TOP (opcode 0x1D)
  pushCommand(0x1Du32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_dom_get_body(): int32 {.importc.}
proc bindweb_dom_get_element_by_id(id: cstring; idLen: uint32): int32 {.importc.}
proc bindweb_dom_create_element(tag: cstring; tagLen: uint32): int32 {.importc.}
proc bindweb_dom_create_element_scoped(tag: cstring; tagLen: uint32; scope: cstring; scopeLen: uint32): int32 {.importc.}
proc bindweb_dom_create_comment(text: cstring; textLen: uint32): int32 {.importc.}
proc bindweb_dom_create_text_node(text: cstring; textLen: uint32): int32 {.importc.}
proc bindweb_dom_get_attribute(handle: int32; name: cstring; nameLen: uint32): uint32 {.importc.}

proc get_body*(): DOMElementHandle =
  ## dom.GET_BODY
  flush()
  return DOMElementHandle(bindweb_dom_get_body())

proc get_element_by_id*(id: string): DOMElementHandle =
  ## dom.GET_ELEMENT_BY_ID
  flush()
  return DOMElementHandle(bindweb_dom_get_element_by_id(id.cstring, id.len.uint32))

proc create_element*(tag: string): DOMElementHandle =
  ## dom.CREATE_ELEMENT
  flush()
  return DOMElementHandle(bindweb_dom_create_element(tag.cstring, tag.len.uint32))

proc create_element_scoped*(tag: string; scope: string): DOMElementHandle =
  ## dom.CREATE_ELEMENT_SCOPED
  flush()
  return DOMElementHandle(bindweb_dom_create_element_scoped(tag.cstring, tag.len.uint32, scope.cstring, scope.len.uint32))

proc create_comment*(text: string): DOMElementHandle =
  ## dom.CREATE_COMMENT
  flush()
  return DOMElementHandle(bindweb_dom_create_comment(text.cstring, text.len.uint32))

proc create_text_node*(text: string): DOMElementHandle =
  ## dom.CREATE_TEXT_NODE
  flush()
  return DOMElementHandle(bindweb_dom_create_text_node(text.cstring, text.len.uint32))

proc get_attribute*(handle: DOMElementHandle; name: string): string =
  ## dom.GET_ATTRIBUTE
  flush()
  let strLen = bindweb_dom_get_attribute(int32(handle), name.cstring, name.len.uint32)
  let data = cast[cstring](bindwebScratchBufferData())
  result = newString(strLen.int)
  if strLen > 0:
    copyMem(addr result[0], data, strLen.int)

