
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## FETCH namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  SUCCESS_EVENT_OPCODE* = 0x10'u8
  ERROR_EVENT_OPCODE* = 0x11'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  SuccessEvent* = object
    ## Event: SUCCESS (opcode 0x10)
    id*: FetchRequestHandle
    data*: string

  ErrorEvent* = object
    ## Event: ERROR (opcode 0x11)
    id*: FetchRequestHandle
    error*: string

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parseSuccessEvent*(data: ptr uint8; len: uint32): SuccessEvent =
  ## Parse SUCCESS event from raw event buffer data.
  var offset: uint32 = 0
  result.id = cast[FetchRequestHandle](readInt32(data, offset))
  result.data = readString(data, offset)

proc parseErrorEvent*(data: ptr uint8; len: uint32): ErrorEvent =
  ## Parse ERROR event from raw event buffer data.
  var offset: uint32 = 0
  result.id = cast[FetchRequestHandle](readInt32(data, offset))
  result.error = readString(data, offset)


# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_fetch_get(url: cstring; urlLen: uint32; headers: cstring; headersLen: uint32): int32 {.importc.}
proc bindweb_fetch_post(url: cstring; urlLen: uint32; body: cstring; bodyLen: uint32; headers: cstring; headersLen: uint32): int32 {.importc.}
proc bindweb_fetch_patch(url: cstring; urlLen: uint32; body: cstring; bodyLen: uint32; headers: cstring; headersLen: uint32): int32 {.importc.}

proc get*(url: string; headers: string): FetchRequestHandle =
  ## fetch.GET
  flush()
  return FetchRequestHandle(bindweb_fetch_get(url.cstring, url.len.uint32, headers.cstring, headers.len.uint32))

proc post*(url: string; body: string; headers: string): FetchRequestHandle =
  ## fetch.POST
  flush()
  return FetchRequestHandle(bindweb_fetch_post(url.cstring, url.len.uint32, body.cstring, body.len.uint32, headers.cstring, headers.len.uint32))

proc patch*(url: string; body: string; headers: string): FetchRequestHandle =
  ## fetch.PATCH
  flush()
  return FetchRequestHandle(bindweb_fetch_patch(url.cstring, url.len.uint32, body.cstring, body.len.uint32, headers.cstring, headers.len.uint32))

