
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## Typed handle definitions

import bindwebtypes

export Handle

type
  DOMElementHandle* = distinct int32
    ## Handle for DOMElement
    ## Inherits from Handle

  CanvasHandle* = distinct int32
    ## Handle for Canvas
    ## Inherits from DOMElementHandle

  CanvasContext2DHandle* = distinct int32
    ## Handle for CanvasContext2D
    ## Inherits from Handle

  WebGLContextHandle* = distinct int32
    ## Handle for WebGLContext
    ## Inherits from Handle

  WGPUContextHandle* = distinct int32
    ## Handle for WGPUContext
    ## Inherits from Handle

  ImageHandle* = distinct int32
    ## Handle for Image
    ## Inherits from DOMElementHandle

  AudioHandle* = distinct int32
    ## Handle for Audio
    ## Inherits from DOMElementHandle

  WebSocketHandle* = distinct int32
    ## Handle for WebSocket
    ## Inherits from Handle

  FetchRequestHandle* = distinct int32
    ## Handle for FetchRequest
    ## Inherits from Handle

  WebGLShaderHandle* = distinct int32
    ## Handle for WebGLShader
    ## Inherits from Handle

  WebGLProgramHandle* = distinct int32
    ## Handle for WebGLProgram
    ## Inherits from Handle

  WebGLBufferHandle* = distinct int32
    ## Handle for WebGLBuffer
    ## Inherits from Handle

  WebGLUniformHandle* = distinct int32
    ## Handle for WebGLUniform
    ## Inherits from Handle

  WGPUAdapterHandle* = distinct int32
    ## Handle for WGPUAdapter
    ## Inherits from Handle

  WGPUQueueHandle* = distinct int32
    ## Handle for WGPUQueue
    ## Inherits from Handle

  WGPUDeviceHandle* = distinct int32
    ## Handle for WGPUDevice
    ## Inherits from Handle

  WGPUShaderModuleHandle* = distinct int32
    ## Handle for WGPUShaderModule
    ## Inherits from Handle

  WGPUCommandEncoderHandle* = distinct int32
    ## Handle for WGPUCommandEncoder
    ## Inherits from Handle

  WGPUTextureViewHandle* = distinct int32
    ## Handle for WGPUTextureView
    ## Inherits from Handle

  WGPURenderPassHandle* = distinct int32
    ## Handle for WGPURenderPass
    ## Inherits from Handle

  WGPUCommandBufferHandle* = distinct int32
    ## Handle for WGPUCommandBuffer
    ## Inherits from Handle

  WGPURenderPipelineHandle* = distinct int32
    ## Handle for WGPURenderPipeline
    ## Inherits from Handle

# ------------------------------------------------------------------------------
# Inheritance converters
# ------------------------------------------------------------------------------

converter toDOMElementHandle*(h: CanvasHandle): DOMElementHandle =
  DOMElementHandle(h.int32)

converter toDOMElementHandle*(h: ImageHandle): DOMElementHandle =
  DOMElementHandle(h.int32)

converter toDOMElementHandle*(h: AudioHandle): DOMElementHandle =
  DOMElementHandle(h.int32)

# ------------------------------------------------------------------------------
# Handle comparison operators
# ------------------------------------------------------------------------------

proc `==`*(a, b: DOMElementHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: DOMElementHandle): bool = a.int32 != b.int32
proc isValid*(h: DOMElementHandle): bool = h.int32 != 0

proc `==`*(a, b: CanvasHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: CanvasHandle): bool = a.int32 != b.int32
proc isValid*(h: CanvasHandle): bool = h.int32 != 0

proc `==`*(a, b: CanvasContext2DHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: CanvasContext2DHandle): bool = a.int32 != b.int32
proc isValid*(h: CanvasContext2DHandle): bool = h.int32 != 0

proc `==`*(a, b: WebGLContextHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebGLContextHandle): bool = a.int32 != b.int32
proc isValid*(h: WebGLContextHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUContextHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUContextHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUContextHandle): bool = h.int32 != 0

proc `==`*(a, b: ImageHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: ImageHandle): bool = a.int32 != b.int32
proc isValid*(h: ImageHandle): bool = h.int32 != 0

proc `==`*(a, b: AudioHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: AudioHandle): bool = a.int32 != b.int32
proc isValid*(h: AudioHandle): bool = h.int32 != 0

proc `==`*(a, b: WebSocketHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebSocketHandle): bool = a.int32 != b.int32
proc isValid*(h: WebSocketHandle): bool = h.int32 != 0

proc `==`*(a, b: FetchRequestHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: FetchRequestHandle): bool = a.int32 != b.int32
proc isValid*(h: FetchRequestHandle): bool = h.int32 != 0

proc `==`*(a, b: WebGLShaderHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebGLShaderHandle): bool = a.int32 != b.int32
proc isValid*(h: WebGLShaderHandle): bool = h.int32 != 0

proc `==`*(a, b: WebGLProgramHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebGLProgramHandle): bool = a.int32 != b.int32
proc isValid*(h: WebGLProgramHandle): bool = h.int32 != 0

proc `==`*(a, b: WebGLBufferHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebGLBufferHandle): bool = a.int32 != b.int32
proc isValid*(h: WebGLBufferHandle): bool = h.int32 != 0

proc `==`*(a, b: WebGLUniformHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WebGLUniformHandle): bool = a.int32 != b.int32
proc isValid*(h: WebGLUniformHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUAdapterHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUAdapterHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUAdapterHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUQueueHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUQueueHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUQueueHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUDeviceHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUDeviceHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUDeviceHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUShaderModuleHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUShaderModuleHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUShaderModuleHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUCommandEncoderHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUCommandEncoderHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUCommandEncoderHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUTextureViewHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUTextureViewHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUTextureViewHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPURenderPassHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPURenderPassHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPURenderPassHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPUCommandBufferHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPUCommandBufferHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPUCommandBufferHandle): bool = h.int32 != 0

proc `==`*(a, b: WGPURenderPipelineHandle): bool = a.int32 == b.int32
proc `!=`*(a, b: WGPURenderPipelineHandle): bool = a.int32 != b.int32
proc isValid*(h: WGPURenderPipelineHandle): bool = h.int32 != 0

