
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## IMAGE namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_image_load(src: cstring; srcLen: uint32): int32 {.importc.}

proc load*(src: string): ImageHandle =
  ## image.LOAD
  flush()
  return ImageHandle(bindweb_image_load(src.cstring, src.len.uint32))

