
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## INPUT namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  KEY_DOWN_EVENT_OPCODE* = 0x05'u8
  KEY_UP_EVENT_OPCODE* = 0x06'u8
  MOUSE_DOWN_EVENT_OPCODE* = 0x07'u8
  MOUSE_UP_EVENT_OPCODE* = 0x08'u8
  MOUSE_MOVE_EVENT_OPCODE* = 0x09'u8
  MOUSE_WHEEL_EVENT_OPCODE* = 0x14'u8
  RESIZE_EVENT_OPCODE* = 0x15'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  KeyDownEvent* = object
    ## Event: KEY_DOWN (opcode 0x05)
    key_code*: int32

  KeyUpEvent* = object
    ## Event: KEY_UP (opcode 0x06)
    key_code*: int32

  MouseDownEvent* = object
    ## Event: MOUSE_DOWN (opcode 0x07)
    button*: int32
    x*: int32
    y*: int32

  MouseUpEvent* = object
    ## Event: MOUSE_UP (opcode 0x08)
    button*: int32
    x*: int32
    y*: int32

  MouseMoveEvent* = object
    ## Event: MOUSE_MOVE (opcode 0x09)
    x*: int32
    y*: int32

  MouseWheelEvent* = object
    ## Event: MOUSE_WHEEL (opcode 0x14)
    delta_x*: int32
    delta_y*: int32

  ResizeEvent* = object
    ## Event: RESIZE (opcode 0x15)
    width*: int32
    height*: int32

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parseKeyDownEvent*(data: ptr uint8; len: uint32): KeyDownEvent =
  ## Parse KEY_DOWN event from raw event buffer data.
  var offset: uint32 = 0
  result.key_code = cast[int32](readInt32(data, offset))

proc parseKeyUpEvent*(data: ptr uint8; len: uint32): KeyUpEvent =
  ## Parse KEY_UP event from raw event buffer data.
  var offset: uint32 = 0
  result.key_code = cast[int32](readInt32(data, offset))

proc parseMouseDownEvent*(data: ptr uint8; len: uint32): MouseDownEvent =
  ## Parse MOUSE_DOWN event from raw event buffer data.
  var offset: uint32 = 0
  result.button = cast[int32](readInt32(data, offset))
  result.x = cast[int32](readInt32(data, offset))
  result.y = cast[int32](readInt32(data, offset))

proc parseMouseUpEvent*(data: ptr uint8; len: uint32): MouseUpEvent =
  ## Parse MOUSE_UP event from raw event buffer data.
  var offset: uint32 = 0
  result.button = cast[int32](readInt32(data, offset))
  result.x = cast[int32](readInt32(data, offset))
  result.y = cast[int32](readInt32(data, offset))

proc parseMouseMoveEvent*(data: ptr uint8; len: uint32): MouseMoveEvent =
  ## Parse MOUSE_MOVE event from raw event buffer data.
  var offset: uint32 = 0
  result.x = cast[int32](readInt32(data, offset))
  result.y = cast[int32](readInt32(data, offset))

proc parseMouseWheelEvent*(data: ptr uint8; len: uint32): MouseWheelEvent =
  ## Parse MOUSE_WHEEL event from raw event buffer data.
  var offset: uint32 = 0
  result.delta_x = cast[int32](readInt32(data, offset))
  result.delta_y = cast[int32](readInt32(data, offset))

proc parseResizeEvent*(data: ptr uint8; len: uint32): ResizeEvent =
  ## Parse RESIZE event from raw event buffer data.
  var offset: uint32 = 0
  result.width = cast[int32](readInt32(data, offset))
  result.height = cast[int32](readInt32(data, offset))


# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc init_keyboard*() =
  ## input.INIT_KEYBOARD (opcode 0x53)
  pushCommand(0x53u32)

proc init_mouse*(handle: DOMElementHandle) =
  ## input.INIT_MOUSE (opcode 0x54)
  pushCommand(0x54u32)
  pushData(handle.int32)

proc exit_pointer_lock*() =
  ## input.EXIT_POINTER_LOCK (opcode 0x55)
  pushCommand(0x55u32)

proc init_mouse_wheel*(handle: DOMElementHandle) =
  ## input.INIT_MOUSE_WHEEL (opcode 0x98)
  pushCommand(0x98u32)
  pushData(handle.int32)

proc init_resize*() =
  ## input.INIT_RESIZE (opcode 0x99)
  pushCommand(0x99u32)

