
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## STORAGE namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc set_item*(key: string, value: string) =
  ## storage.SET_ITEM (opcode 0x67)
  pushCommand(0x67u32)
  pushString(key)
  pushString(value)

proc remove_item*(key: string) =
  ## storage.REMOVE_ITEM (opcode 0x68)
  pushCommand(0x68u32)
  pushString(key)

proc clear*() =
  ## storage.CLEAR (opcode 0x69)
  pushCommand(0x69u32)

