
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## SYSTEM namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  POPSTATE_EVENT_OPCODE* = 0x0A'u8
  VISIBILITY_CHANGE_EVENT_OPCODE* = 0x0B'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  PopstateEvent* = object
    ## Event: POPSTATE (opcode 0x0A)
    path*: string

  VisibilityChangeEvent* = object
    ## Event: VISIBILITY_CHANGE (opcode 0x0B)
    hidden*: uint8
    state*: string

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parsePopstateEvent*(data: ptr uint8; len: uint32): PopstateEvent =
  ## Parse POPSTATE event from raw event buffer data.
  var offset: uint32 = 0
  result.path = readString(data, offset)

proc parseVisibilityChangeEvent*(data: ptr uint8; len: uint32): VisibilityChangeEvent =
  ## Parse VISIBILITY_CHANGE event from raw event buffer data.
  var offset: uint32 = 0
  result.hidden = uint8(readUint32(data, offset))
  result.state = readString(data, offset)


# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc log*(msg: string) =
  ## system.LOG (opcode 0x56)
  pushCommand(0x56u32)
  pushString(msg)

proc warn*(msg: string) =
  ## system.WARN (opcode 0x57)
  pushCommand(0x57u32)
  pushString(msg)

proc error*(msg: string) =
  ## system.ERROR (opcode 0x58)
  pushCommand(0x58u32)
  pushString(msg)

proc set_main_loop*(fn: pointer) =
  ## system.SET_MAIN_LOOP (opcode 0x59)
  pushCommand(0x59u32)
  pushData(cast[uint32](fn))

proc set_title*(title: string) =
  ## system.SET_TITLE (opcode 0x5A)
  pushCommand(0x5Au32)
  pushString(title)

proc reload*() =
  ## system.RELOAD (opcode 0x5B)
  pushCommand(0x5Bu32)

proc open_url*(url: string) =
  ## system.OPEN_URL (opcode 0x5C)
  pushCommand(0x5Cu32)
  pushString(url)

proc push_state*(path: string) =
  ## system.PUSH_STATE (opcode 0x64)
  pushCommand(0x64u32)
  pushString(path)

proc init_popstate*() =
  ## system.INIT_POPSTATE (opcode 0x65)
  pushCommand(0x65u32)

proc init_visibility_change*() =
  ## system.INIT_VISIBILITY_CHANGE (opcode 0x66)
  pushCommand(0x66u32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_system_get_time(): float64 {.importc.}
proc bindweb_system_get_date_now(): float64 {.importc.}
proc bindweb_system_get_pathname(): uint32 {.importc.}
proc bindweb_system_get_search(): uint32 {.importc.}
proc bindweb_system_get_query_param(name: cstring; nameLen: uint32): uint32 {.importc.}
proc bindweb_system_get_visibility_state(): uint32 {.importc.}
proc bindweb_system_is_hidden(): uint8 {.importc.}

proc get_time*(): float64 =
  ## system.GET_TIME
  flush()
  return bindweb_system_get_time()

proc get_date_now*(): float64 =
  ## system.GET_DATE_NOW
  flush()
  return bindweb_system_get_date_now()

proc get_pathname*(): string =
  ## system.GET_PATHNAME
  flush()
  let strLen = bindweb_system_get_pathname()
  let data = cast[cstring](bindwebScratchBufferData())
  result = newString(strLen.int)
  if strLen > 0:
    copyMem(addr result[0], data, strLen.int)

proc get_search*(): string =
  ## system.GET_SEARCH
  flush()
  let strLen = bindweb_system_get_search()
  let data = cast[cstring](bindwebScratchBufferData())
  result = newString(strLen.int)
  if strLen > 0:
    copyMem(addr result[0], data, strLen.int)

proc get_query_param*(name: string): string =
  ## system.GET_QUERY_PARAM
  flush()
  let strLen = bindweb_system_get_query_param(name.cstring, name.len.uint32)
  let data = cast[cstring](bindwebScratchBufferData())
  result = newString(strLen.int)
  if strLen > 0:
    copyMem(addr result[0], data, strLen.int)

proc get_visibility_state*(): string =
  ## system.GET_VISIBILITY_STATE
  flush()
  let strLen = bindweb_system_get_visibility_state()
  let data = cast[cstring](bindwebScratchBufferData())
  result = newString(strLen.int)
  if strLen > 0:
    copyMem(addr result[0], data, strLen.int)

proc is_hidden*(): uint8 =
  ## system.IS_HIDDEN
  flush()
  return bindweb_system_is_hidden().uint8

