
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## WEBGL namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc viewport*(ctx_handle: WebGLContextHandle, x: int32, y: int32, width: int32, height: int32) =
  ## webgl.VIEWPORT (opcode 0x78)
  pushCommand(0x78u32)
  pushData(ctx_handle.int32)
  pushData(x.int32)
  pushData(y.int32)
  pushData(width.int32)
  pushData(height.int32)

proc clear_color*(ctx_handle: WebGLContextHandle, r: float64, g: float64, b: float64, a: float64) =
  ## webgl.CLEAR_COLOR (opcode 0x79)
  pushCommand(0x79u32)
  pushData(ctx_handle.int32)
  pushData(r.float64)
  pushData(g.float64)
  pushData(b.float64)
  pushData(a.float64)

proc clear*(ctx_handle: WebGLContextHandle, mask: uint32) =
  ## webgl.CLEAR (opcode 0x7A)
  pushCommand(0x7Au32)
  pushData(ctx_handle.int32)
  pushData(mask.uint32)

proc attach_shader*(ctx_handle: WebGLContextHandle, prog_handle: WebGLProgramHandle, shader_handle: WebGLShaderHandle) =
  ## webgl.ATTACH_SHADER (opcode 0x7D)
  pushCommand(0x7Du32)
  pushData(ctx_handle.int32)
  pushData(prog_handle.int32)
  pushData(shader_handle.int32)

proc link_program*(ctx_handle: WebGLContextHandle, prog_handle: WebGLProgramHandle) =
  ## webgl.LINK_PROGRAM (opcode 0x7E)
  pushCommand(0x7Eu32)
  pushData(ctx_handle.int32)
  pushData(prog_handle.int32)

proc bind_attrib_location*(ctx_handle: WebGLContextHandle, prog_handle: WebGLProgramHandle, index: uint32, name: string) =
  ## webgl.BIND_ATTRIB_LOCATION (opcode 0x7F)
  pushCommand(0x7Fu32)
  pushData(ctx_handle.int32)
  pushData(prog_handle.int32)
  pushData(index.uint32)
  pushString(name)

proc use_program*(ctx_handle: WebGLContextHandle, prog_handle: WebGLProgramHandle) =
  ## webgl.USE_PROGRAM (opcode 0x80)
  pushCommand(0x80u32)
  pushData(ctx_handle.int32)
  pushData(prog_handle.int32)

proc bind_buffer*(ctx_handle: WebGLContextHandle, target: uint32, buf_handle: WebGLBufferHandle) =
  ## webgl.BIND_BUFFER (opcode 0x82)
  pushCommand(0x82u32)
  pushData(ctx_handle.int32)
  pushData(target.uint32)
  pushData(buf_handle.int32)

proc buffer_data*(ctx_handle: WebGLContextHandle, target: uint32, data_ptr: uint32, data_len: uint32, usage: uint32) =
  ## webgl.BUFFER_DATA (opcode 0x83)
  pushCommand(0x83u32)
  pushData(ctx_handle.int32)
  pushData(target.uint32)
  pushData(data_ptr.uint32)
  pushData(data_len.uint32)
  pushData(usage.uint32)

proc enable_vertex_attrib_array*(ctx_handle: WebGLContextHandle, index: uint32) =
  ## webgl.ENABLE_VERTEX_ATTRIB_ARRAY (opcode 0x84)
  pushCommand(0x84u32)
  pushData(ctx_handle.int32)
  pushData(index.uint32)

proc enable*(ctx_handle: WebGLContextHandle, cap: uint32) =
  ## webgl.ENABLE (opcode 0x85)
  pushCommand(0x85u32)
  pushData(ctx_handle.int32)
  pushData(cap.uint32)

proc uniform_1f*(ctx_handle: WebGLContextHandle, loc_handle: WebGLUniformHandle, val: float64) =
  ## webgl.UNIFORM_1F (opcode 0x87)
  pushCommand(0x87u32)
  pushData(ctx_handle.int32)
  pushData(loc_handle.int32)
  pushData(val.float64)

proc vertex_attrib_pointer*(ctx_handle: WebGLContextHandle, index: uint32, size: int32, typ: uint32, normalized: uint8, stride: int32, offset: int32) =
  ## webgl.VERTEX_ATTRIB_POINTER (opcode 0x88)
  pushCommand(0x88u32)
  pushData(ctx_handle.int32)
  pushData(index.uint32)
  pushData(size.int32)
  pushData(typ.uint32)
  pushData(normalized.uint32)
  pushData(stride.int32)
  pushData(offset.int32)

proc draw_arrays*(ctx_handle: WebGLContextHandle, mode: uint32, first: int32, count: int32) =
  ## webgl.DRAW_ARRAYS (opcode 0x89)
  pushCommand(0x89u32)
  pushData(ctx_handle.int32)
  pushData(mode.uint32)
  pushData(first.int32)
  pushData(count.int32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_webgl_create_shader(ctx_handle: int32; typ: uint32; source: cstring; sourceLen: uint32): int32 {.importc.}
proc bindweb_webgl_create_program(ctx_handle: int32): int32 {.importc.}
proc bindweb_webgl_create_buffer(ctx_handle: int32): int32 {.importc.}
proc bindweb_webgl_get_uniform_location(ctx_handle: int32; prog_handle: int32; name: cstring; nameLen: uint32): int32 {.importc.}

proc create_shader*(ctx_handle: WebGLContextHandle; typ: uint32; source: string): WebGLShaderHandle =
  ## webgl.CREATE_SHADER
  flush()
  return WebGLShaderHandle(bindweb_webgl_create_shader(int32(ctx_handle), typ, source.cstring, source.len.uint32))

proc create_program*(ctx_handle: WebGLContextHandle): WebGLProgramHandle =
  ## webgl.CREATE_PROGRAM
  flush()
  return WebGLProgramHandle(bindweb_webgl_create_program(int32(ctx_handle)))

proc create_buffer*(ctx_handle: WebGLContextHandle): WebGLBufferHandle =
  ## webgl.CREATE_BUFFER
  flush()
  return WebGLBufferHandle(bindweb_webgl_create_buffer(int32(ctx_handle)))

proc get_uniform_location*(ctx_handle: WebGLContextHandle; prog_handle: WebGLProgramHandle; name: string): WebGLUniformHandle =
  ## webgl.GET_UNIFORM_LOCATION
  flush()
  return WebGLUniformHandle(bindweb_webgl_get_uniform_location(int32(ctx_handle), int32(prog_handle), name.cstring, name.len.uint32))

