
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## WEBSOCKET namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  MESSAGE_EVENT_OPCODE* = 0x0C'u8
  OPEN_EVENT_OPCODE* = 0x0D'u8
  CLOSE_EVENT_OPCODE* = 0x0E'u8
  ERROR_EVENT_OPCODE* = 0x0F'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  MessageEvent* = object
    ## Event: MESSAGE (opcode 0x0C)
    handle*: WebSocketHandle
    data*: string

  OpenEvent* = object
    ## Event: OPEN (opcode 0x0D)
    handle*: WebSocketHandle

  CloseEvent* = object
    ## Event: CLOSE (opcode 0x0E)
    handle*: WebSocketHandle

  ErrorEvent* = object
    ## Event: ERROR (opcode 0x0F)
    handle*: WebSocketHandle

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parseMessageEvent*(data: ptr uint8; len: uint32): MessageEvent =
  ## Parse MESSAGE event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WebSocketHandle](readInt32(data, offset))
  result.data = readString(data, offset)

proc parseOpenEvent*(data: ptr uint8; len: uint32): OpenEvent =
  ## Parse OPEN event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WebSocketHandle](readInt32(data, offset))

proc parseCloseEvent*(data: ptr uint8; len: uint32): CloseEvent =
  ## Parse CLOSE event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WebSocketHandle](readInt32(data, offset))

proc parseErrorEvent*(data: ptr uint8; len: uint32): ErrorEvent =
  ## Parse ERROR event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WebSocketHandle](readInt32(data, offset))


# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc send*(handle: WebSocketHandle, msg: string) =
  ## websocket.SEND (opcode 0x72)
  pushCommand(0x72u32)
  pushData(handle.int32)
  pushString(msg)

proc close*(handle: WebSocketHandle) =
  ## websocket.CLOSE (opcode 0x73)
  pushCommand(0x73u32)
  pushData(handle.int32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_websocket_connect(url: cstring; urlLen: uint32): int32 {.importc.}

proc connect*(url: string): WebSocketHandle =
  ## websocket.CONNECT
  flush()
  return WebSocketHandle(bindweb_websocket_connect(url.cstring, url.len.uint32))

