
## Generated by WebCC - DO NOT EDIT
## Source: schema.def

## WGPU namespace API

import bindweb, bindwebtypes

import handles

# ------------------------------------------------------------------------------
# Event opcode constants
# ------------------------------------------------------------------------------

const
  ADAPTER_READY_EVENT_OPCODE* = 0x12'u8
  DEVICE_READY_EVENT_OPCODE* = 0x13'u8

# ------------------------------------------------------------------------------
# Event types
# ------------------------------------------------------------------------------

type
  AdapterReadyEvent* = object
    ## Event: ADAPTER_READY (opcode 0x12)
    handle*: WGPUAdapterHandle

  DeviceReadyEvent* = object
    ## Event: DEVICE_READY (opcode 0x13)
    handle*: WGPUDeviceHandle

# ------------------------------------------------------------------------------
# Event parsing
# ------------------------------------------------------------------------------

proc parseAdapterReadyEvent*(data: ptr uint8; len: uint32): AdapterReadyEvent =
  ## Parse ADAPTER_READY event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WGPUAdapterHandle](readInt32(data, offset))

proc parseDeviceReadyEvent*(data: ptr uint8; len: uint32): DeviceReadyEvent =
  ## Parse DEVICE_READY event from raw event buffer data.
  var offset: uint32 = 0
  result.handle = cast[WGPUDeviceHandle](readInt32(data, offset))


# ------------------------------------------------------------------------------
# Void commands (push to command buffer)
# ------------------------------------------------------------------------------

proc request_adapter*() =
  ## wgpu.REQUEST_ADAPTER (opcode 0x8A)
  pushCommand(0x8Au32)

proc request_device*(adapter_handle: WGPUAdapterHandle) =
  ## wgpu.REQUEST_DEVICE (opcode 0x8B)
  pushCommand(0x8Bu32)
  pushData(adapter_handle.int32)

proc configure*(context_handle: WGPUContextHandle, device_handle: WGPUDeviceHandle, format: string) =
  ## wgpu.CONFIGURE (opcode 0x8F)
  pushCommand(0x8Fu32)
  pushData(context_handle.int32)
  pushData(device_handle.int32)
  pushString(format)

proc end_pass*(pass_handle: WGPURenderPassHandle) =
  ## wgpu.END_PASS (opcode 0x92)
  pushCommand(0x92u32)
  pushData(pass_handle.int32)

proc queue_submit*(queue_handle: WGPUQueueHandle, command_buffer_handle: WGPUCommandBufferHandle) =
  ## wgpu.QUEUE_SUBMIT (opcode 0x94)
  pushCommand(0x94u32)
  pushData(queue_handle.int32)
  pushData(command_buffer_handle.int32)

proc set_pipeline*(pass_handle: WGPURenderPassHandle, pipeline_handle: WGPURenderPipelineHandle) =
  ## wgpu.SET_PIPELINE (opcode 0x96)
  pushCommand(0x96u32)
  pushData(pass_handle.int32)
  pushData(pipeline_handle.int32)

proc draw*(pass_handle: WGPURenderPassHandle, vertex_count: int32, instance_count: int32, first_vertex: int32, first_instance: int32) =
  ## wgpu.DRAW (opcode 0x97)
  pushCommand(0x97u32)
  pushData(pass_handle.int32)
  pushData(vertex_count.int32)
  pushData(instance_count.int32)
  pushData(first_vertex.int32)
  pushData(first_instance.int32)

# ------------------------------------------------------------------------------
# Return-value commands (JS imports)
# ------------------------------------------------------------------------------

proc bindweb_wgpu_get_queue(device_handle: int32): int32 {.importc.}
proc bindweb_wgpu_create_shader_module(device_handle: int32; code: cstring; codeLen: uint32): int32 {.importc.}
proc bindweb_wgpu_create_command_encoder(device_handle: int32): int32 {.importc.}
proc bindweb_wgpu_get_current_texture_view(context_handle: int32): int32 {.importc.}
proc bindweb_wgpu_begin_render_pass(encoder_handle: int32; view_handle: int32; r: float64; g: float64; b: float64; a: float64): int32 {.importc.}
proc bindweb_wgpu_finish_encoder(encoder_handle: int32): int32 {.importc.}
proc bindweb_wgpu_create_render_pipeline_simple(device_handle: int32; vs_module_handle: int32; fs_module_handle: int32; vs_entry: cstring; vs_entryLen: uint32; fs_entry: cstring; fs_entryLen: uint32; format: cstring; formatLen: uint32): int32 {.importc.}

proc get_queue*(device_handle: WGPUDeviceHandle): WGPUQueueHandle =
  ## wgpu.GET_QUEUE
  flush()
  return WGPUQueueHandle(bindweb_wgpu_get_queue(int32(device_handle)))

proc create_shader_module*(device_handle: WGPUDeviceHandle; code: string): WGPUShaderModuleHandle =
  ## wgpu.CREATE_SHADER_MODULE
  flush()
  return WGPUShaderModuleHandle(bindweb_wgpu_create_shader_module(int32(device_handle), code.cstring, code.len.uint32))

proc create_command_encoder*(device_handle: WGPUDeviceHandle): WGPUCommandEncoderHandle =
  ## wgpu.CREATE_COMMAND_ENCODER
  flush()
  return WGPUCommandEncoderHandle(bindweb_wgpu_create_command_encoder(int32(device_handle)))

proc get_current_texture_view*(context_handle: WGPUContextHandle): WGPUTextureViewHandle =
  ## wgpu.GET_CURRENT_TEXTURE_VIEW
  flush()
  return WGPUTextureViewHandle(bindweb_wgpu_get_current_texture_view(int32(context_handle)))

proc begin_render_pass*(encoder_handle: WGPUCommandEncoderHandle; view_handle: WGPUTextureViewHandle; r: float64; g: float64; b: float64; a: float64): WGPURenderPassHandle =
  ## wgpu.BEGIN_RENDER_PASS
  flush()
  return WGPURenderPassHandle(bindweb_wgpu_begin_render_pass(int32(encoder_handle), int32(view_handle), r, g, b, a))

proc finish_encoder*(encoder_handle: WGPUCommandEncoderHandle): WGPUCommandBufferHandle =
  ## wgpu.FINISH_ENCODER
  flush()
  return WGPUCommandBufferHandle(bindweb_wgpu_finish_encoder(int32(encoder_handle)))

proc create_render_pipeline_simple*(device_handle: WGPUDeviceHandle; vs_module_handle: WGPUShaderModuleHandle; fs_module_handle: WGPUShaderModuleHandle; vs_entry: string; fs_entry: string; format: string): WGPURenderPipelineHandle =
  ## wgpu.CREATE_RENDER_PIPELINE_SIMPLE
  flush()
  return WGPURenderPipelineHandle(bindweb_wgpu_create_render_pipeline_simple(int32(device_handle), int32(vs_module_handle), int32(fs_module_handle), vs_entry.cstring, vs_entry.len.uint32, fs_entry.cstring, fs_entry.len.uint32, format.cstring, format.len.uint32))

